/**
 * Edison Law content. Turn development on or off in config.js.
 */
import { config } from "./config.js";

export const site = {
  mode: config.develop ? "development" : "production",
  canonicalOrigin: "https://edisonlaw.co.uk",
  name: "Edison Law",
  descriptor: "Law Firm · London",
  masterLine: "Following digital evidence. Building legal cases.",
  shortLine: "Editorial forensics for modern legal work.",
  lang: "en-GB",
  locale: "en_GB",
  themeColor: "#0A2028",
  backgroundColor: "#F1F6F4",
  sraNumber: "510498",
  sraUrl: "https://www.sra.org.uk/consumers/register/organisation/?sraNumber=510498",
  sraSince: "1 November 2015",
  email: "abi.wills@edisonlaw.co.uk",
  emailSource: "public directory — confirm before launch",
  phone: "",
  address: {
    line1: "12 Augustus Road",
    line2: "Wimbledon",
    city: "London",
    postcode: "SW19 6LN",
    country: "England",
  },
  analytics: { enabled: config.analytics },
  search: { enabled: config.search },

  nav: [
    { label: "Expertise", href: "/expertise/" },
    { label: "Insights", href: "/insights/" },
    { label: "People", href: "/people/" },
    { label: "About", href: "/about/" },
    { label: "Contact", href: "/contact/", kind: "button" },
  ],

  rail: [
    { label: "Expertise", href: "/expertise/" },
    { label: "Investigations", href: "/insights/" },
    { label: "Insights", href: "/insights/" },
    { label: "People", href: "/people/" },
    { label: "About", href: "/about/" },
    { label: "Contact", href: "/contact/" },
  ],

  footerLinks: [
    { label: "Legal & regulatory", href: "/legal-regulatory/" },
    { label: "Pricing", href: "/pricing/" },
    { label: "Complaints", href: "/complaints/" },
    { label: "Privacy", href: "/privacy/" },
    { label: "Cookies", href: "/cookies/" },
    { label: "Accessibility", href: "/accessibility/" },
    { label: "Fraud warning", href: "/fraud-warning/" },
  ],

  practices: [
    {
      id: "financial-crime",
      index: "01",
      title: "Financial crime",
      href: "/expertise/financial-crime/",
      summary: "Investigations, defence and advisory work where the facts sit across companies, accounts and people.",
    },
    {
      id: "tax",
      index: "02",
      title: "Tax disputes & resolution",
      href: "/expertise/tax-disputes-resolution/",
      summary: "HMRC enquiries, disclosure and settlement, and litigation support when the numbers and the law diverge.",
    },
    {
      id: "crypto",
      index: "03",
      title: "Crypto investigations",
      href: "/expertise/crypto-investigations/",
      summary: "Transaction analysis and evidence strategy for matters that begin on-chain and must end in a legal position.",
    },
    {
      id: "digital-assets",
      index: "04",
      title: "Digital asset disputes",
      href: "/expertise/digital-asset-disputes/",
      summary: "Ownership, control and recovery strategy for assets that exist as records rather than objects.",
    },
  ],

  people: [
    {
      slug: "zayn-marin",
      name: "Zayn Marin",
      shortName: "Zayn Marin",
      initials: "ZM",
      role: "Financial Forensic Expert",
      firm: "Edison Law",
      photo: "/images/people/zayn-marin.png",
      photoWidth: 472,
      photoHeight: 472,
      summary:
        "The firm's in-house financial forensic expert. Turns disordered financial material into evidence a court will accept, from first suspicion through trial, confiscation and recovery.",
      bio: [
        "Zayn is the firm's in-house financial forensic expert. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Zayn's role is the one that makes that record possible: he turns disordered financial material into evidence a court will accept.",
        "He works for companies, organisations and individuals who have been the victims of crime, and is usually involved from the first meeting onward. Where a client arrives with a suspicion, a gap in the accounts or an unexplained payment run, Zayn establishes what actually happened — reconstructing ledgers, unwinding intercompany transfers, rebuilding destroyed or manipulated records, quantifying loss and identifying the point at which money left the client's control and where it went next.",
        "Zayn supports the firm's significant experience in the private prosecution of fraud, corporate dishonesty and financial crime by building the financial spine of those cases. He prepares expert reports and schedules for use in the Crown Court, gives evidence at trial, and works closely with counsel to reduce complex financial narratives to something a jury can follow. He is equally comfortable being cross-examined on methodology as he is explaining it to a board that has never seen a forensic report before.",
        "His work is central to recovery. Zayn advises on the best means of retrieving assets linked to the offending by locating them first — tracing funds through bank records, corporate structures, nominee accounts, property transactions and digital wallets, and producing the evidence needed to support freezing, proprietary and disclosure applications at speed. He also quantifies benefit for the purposes of confiscation proceedings and prepares the loss analyses relied on in civil claims, insurance notifications and settlement negotiations.",
        "Alongside investigative work, Zayn advises on regulatory and remedial matters: transaction testing, reconstruction of accounting positions for reporting purposes, assessment of control failures, and the design of monitoring that will detect the same conduct if it recurs.",
        "Zayn is unusually good at the part most experts find difficult — saying clearly what the numbers do and do not prove. Clients value the fact that he will tell them early when a case is stronger than they feared, and just as early when it is not.",
      ],
      experience: [
        "Reconstruction of three years of manipulated management accounts, establishing the mechanism and quantum of a long-running invoicing fraud",
        "Tracing and quantification exercise underpinning an emergency worldwide freezing order",
        "Expert evidence at trial in a private prosecution of a former finance director",
        "Benefit and available amount analysis in confiscation proceedings following conviction",
        "Forensic review of a payments business's transaction records following the discovery of internal fraud",
      ],
    },
    {
      slug: "spencer-espinoza",
      name: "Spencer Espinoza",
      shortName: "Spencer Espinoza",
      initials: "SE",
      role: "Senior Investigator",
      firm: "Edison Law",
      photo: "/images/people/spencer-espinoza.png",
      photoWidth: 472,
      photoHeight: 472,
      summary:
        "Senior investigator in the financial crime team. Deployed at the outset of a matter to gather and preserve the material on which the case depends, in a form that will hold up under scrutiny.",
      bio: [
        "Spencer is a senior investigator within the firm's financial crime team. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Spencer's role is to gather the material on which that work depends — lawfully, thoroughly and in a form that will hold up under scrutiny.",
        "He works for companies, organisations and individuals who have been the victims of crime, and is typically deployed at the outset of a matter, when the priority is to establish the facts before evidence degrades or is deliberately destroyed. Spencer secures and preserves documents and devices, identifies and approaches witnesses, takes statements, conducts surveillance and enquiry agent work where it is proportionate, and carries out the background and open-source research that reveals who a counterparty really is and what they are connected to.",
        "Spencer supports the firm's significant experience in the private prosecution of fraud, corporate dishonesty and financial crime by building case files to a criminal evidential standard from day one. He understands that a private prosecution is judged as harshly as any state prosecution, and that a case can be lost long before trial through poor continuity, unrecorded contact with witnesses or an incomplete disclosure schedule. He therefore works to police-grade discipline: contemporaneous notes, exhibit continuity, properly recorded interviews and full unused material schedules handed to the lawyers ready for review.",
        "His work is directly tied to recovery. Spencer supports advice on the best means of retrieving assets linked to the offending by finding those assets — company and land registry research across multiple jurisdictions, identification of nominees and connected parties, lifestyle and expenditure enquiries, vehicle and property confirmation, and locating individuals who have moved or gone deliberately to ground. His findings frequently form the evidential basis for freezing, search and disclosure applications made at short notice.",
        "Spencer also assists with internal and regulatory investigations, including employee interviews, whistleblower follow-up and factual enquiry supporting self-reports and remediation.",
        "He is calm and unobtrusive in situations that are often tense, and clients frequently comment on how quickly he establishes trust with reluctant witnesses. Colleagues rely on him for something simpler: when Spencer says a fact is confirmed, it is confirmed.",
      ],
      experience: [
        "Preservation of documents and devices at three sites within twenty-four hours of a fraud being discovered",
        "Witness enquiries and statement-taking underpinning a successful private prosecution of a former employee",
        "Asset location exercise identifying property and corporate interests held through connected parties",
        "Tracing and locating a defendant who had relocated overseas, enabling service of proceedings",
        "Background and integrity enquiries revealing an undisclosed relationship between a supplier and an internal budget holder",
      ],
    },
    {
      slug: "sofia-nowak",
      name: "Sofia Nowak",
      shortName: "Sofia Nowak",
      initials: "SN",
      role: "Associate Solicitor — Fraud, Financial Crime & Private Prosecutions",
      firm: "Edison Law",
      photo: "/images/people/sofia-nowak.png",
      photoWidth: 400,
      photoHeight: 560,
      summary:
        "Associate solicitor in the financial crime team. Closely involved in the day-to-day conduct of cases from first instruction through to trial, and often a client's principal point of contact.",
      bio: [
        "Sofia is an associate solicitor in the firm's financial crime team. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Sofia is closely involved in the day-to-day conduct of those cases, from first instruction through to trial.",
        "She acts for companies, organisations and individuals who have been the victims of crime. Her practice covers employee and fiduciary fraud, false accounting, misappropriation of company funds, supplier and invoicing fraud, and investment schemes affecting private individuals. Sofia is often a client's principal point of contact, and she is valued for keeping people properly informed in matters that are frequently distressing as well as complex.",
        "Sofia contributes to the firm's significant experience in the private prosecution of fraud, corporate dishonesty and financial crime. She prepares case papers to a criminal evidential standard, drafts witness statements, manages disclosure and unused material, instructs counsel and experts, and attends court throughout proceedings. She takes seriously the duties that attach to a private prosecutor — candour, disclosure and objectivity — and applies them rigorously, on the understanding that a case brought carelessly will not survive contact with the defence.",
        "She also works on asset recovery, assisting clients on the best means of retrieving assets linked to the offending. Sofia prepares applications for freezing, search and disclosure orders, works with forensic accountants and investigators on tracing exercises, and supports restraint and confiscation proceedings alongside civil and insolvency claims. Much of this work is done at short notice, and she is well suited to it.",
        "Sofia additionally advises on internal investigations and regulatory matters, including reporting obligations, employee interviews and the remedial steps that follow the discovery of misconduct.",
        "She is precise, extremely well organised and notably calm under pressure. Colleagues describe her as the person who has already found the document everyone else is still looking for.",
      ],
      experience: [
        "Preparation of the case file and disclosure schedules in a private prosecution of a former employee for a multi-year invoicing fraud",
        "Assisting on an urgent freezing and search order application following the discovery of fiduciary misappropriation",
        "Acting for individual investors in a collapsed investment scheme, coordinating tracing and civil recovery",
        "Supporting an internal investigation and subsequent report arising from suspected procurement fraud",
        "Preparation of witness evidence and trial bundles in Crown Court proceedings",
      ],
    },
    {
      slug: "eva-adelman",
      name: "Eva Adelman",
      shortName: "Eva Adelman",
      initials: "EA",
      role: "Equity Associate — Fraud, Financial Crime & Private Prosecutions",
      firm: "Edison Law",
      photo: "/images/people/eva-adelman.png",
      photoWidth: 400,
      photoHeight: 560,
      summary:
        "Equity associate in the financial crime team. Combines senior case conduct with a stake in how matters are chosen, resourced and run, and is the principal point of contact for a number of corporate clients.",
      bio: [
        "Eva is an equity associate in the firm's financial crime team, holding a stake in the practice she helps to build. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Eva combines the hands-on case conduct of a senior fee earner with a genuine ownership interest in how the firm's cases are chosen, resourced and run.",
        "She acts for companies, organisations and individuals who have been the victims of crime. Her practice covers corporate fraud and false accounting, misappropriation by directors and senior employees, shareholder and joint venture disputes with a dishonesty element, supplier and procurement fraud, and losses suffered by individuals through misrepresented investments. She runs her own caseload and is the principal point of contact for a number of the firm's corporate clients.",
        "Eva contributes substantially to the firm's significant experience in the private prosecution of fraud, corporate dishonesty and financial crime. She takes cases from initial assessment — advising realistically on merit, cost and the likelihood of recovery before a client commits — through investigation, charge and trial. She is meticulous about the obligations of a private prosecutor, particularly disclosure and the duty of candour, and prepares files on the assumption that every decision taken will later be examined by the defence and the court.",
        "Asset recovery is a defining part of her work. Eva advises clients on the best means of retrieving assets linked to the offending, coordinating criminal restraint and confiscation with civil freezing and proprietary relief, disclosure orders against banks and third parties, and enforcement against property and corporate interests. She works closely with the firm's forensic and investigative teams to ensure recovery strategy is settled at the outset rather than assembled after conviction.",
        "She also advises on internal investigations, whistleblowing complaints, regulatory reporting and the governance failures that fraud tends to expose.",
        "Eva is commercially minded and direct. Clients value the fact that she frames every decision in terms of outcome and cost, and that she is willing to advise against a course of action when the numbers do not support it.",
      ],
      experience: [
        "Conduct of a private prosecution of two directors for false accounting and misappropriation of company funds",
        "Freezing and disclosure orders obtained on short notice, followed by full recovery by negotiated settlement",
        "Acting for a corporate client in parallel criminal, civil and insolvency proceedings arising from supplier fraud",
        "Advising a board on an internal investigation into senior management expenses and subsequent dismissals",
        "Tracing and recovery of funds transferred to family members and connected companies ahead of enforcement",
      ],
    },
    {
      slug: "martin-horak",
      name: "Martin Horák",
      shortName: "Martin Horák",
      initials: "MH",
      role: "Financial Forensic Expert",
      firm: "Edison Law",
      photo: "/images/people/martin-horak.png",
      photoWidth: 472,
      photoHeight: 472,
      summary:
        "Financial forensic expert in the financial crime team. Specialises in data-led investigation: where a case turns on volume, he finds the pattern inside it.",
      bio: [
        "Martin is a financial forensic expert within the firm's financial crime team. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Martin's contribution is analytical: where a case turns on volume — thousands of transactions, years of ledgers, multiple entities and currencies — he is the person who finds the pattern inside it.",
        "He works for companies, organisations and individuals who have been the victims of crime, and specialises in data-led investigation. Martin builds and interrogates transaction datasets, reconciles accounting records against underlying banking movements, tests journal entries and adjustments for manipulation, and identifies the anomalies that reveal how a fraud was constructed and concealed. His work frequently establishes not only that money was taken but precisely when the scheme began — a question that often determines the value of the claim and the scope of the charges.",
        "Martin supports the firm's significant experience in the private prosecution of fraud, corporate dishonesty and financial crime by producing expert evidence capable of withstanding sustained challenge. He prepares reports and schedules for use in the Crown Court, gives oral evidence at trial, and works with counsel to distil large-scale financial analysis into a sequence a jury can follow without losing the detail on which the case depends. He is careful to distinguish between what the data establishes, what it suggests and what it cannot prove — a discipline that makes his evidence difficult to dislodge.",
        "His work feeds directly into recovery. Martin supports advice on the best means of retrieving assets linked to the offending by following value through accounts, intercompany transfers, corporate structures and cross-border payment chains, identifying the point at which proceeds were converted, layered or invested. His analysis regularly underpins urgent freezing and disclosure applications, and he prepares benefit and quantum assessments for confiscation proceedings, civil claims and insurance notification.",
        "With experience across European jurisdictions, Martin is comfortable working with accounting records prepared under different national standards and in multiple languages — a frequent obstacle in cross-border matters, and one that often defeats less experienced analysts.",
        "He also advises clients on control weaknesses exposed by an investigation, and on the transaction monitoring and reconciliation processes needed to detect similar conduct in future.",
        "Martin is understated and exact. Colleagues note that he rarely offers an opinion until the analysis is complete, and that when he does, it holds.",
      ],
      experience: [
        "Analysis of over two million transactions across group entities, establishing the mechanism and start date of a concealed diversion of funds",
        "Journal entry testing that identified systematic year-end manipulation of reported revenue",
        "Expert evidence in Crown Court proceedings following a private prosecution for false accounting",
        "Cross-border tracing analysis supporting a worldwide freezing order in a multi-jurisdictional matter",
        "Quantum and benefit analysis relied on in confiscation proceedings and parallel civil recovery",
      ],
    },
    {
      slug: "vivian-adler",
      name: "Vivian Adler",
      shortName: "Vivian Adler",
      initials: "VA",
      role: "Financial Forensic Expert",
      firm: "Edison Law",
      photo: "/images/people/vivian-adler.png",
      photoWidth: 472,
      photoHeight: 472,
      summary:
        "Financial forensic expert in the financial crime team. Specialises in rapid financial triage and payments tracing in the first hours of a matter, when the question is where the money is right now.",
      bio: [
        "Vivian is a financial forensic expert within the firm's financial crime team. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Vivian's particular strength is speed: she is the person the team turns to in the first hours of a matter, when the question is not yet how a fraud was built but where the money is right now.",
        "She works for companies, organisations and individuals who have been the victims of crime, and specialises in rapid financial triage and payments tracing. Working from incomplete records and under considerable time pressure, Vivian establishes the flow of funds out of a client's control — through payment service providers, correspondent banks, money service businesses, e-money accounts and digital asset platforms — and produces the evidenced picture needed to support an emergency application before the funds are dissipated further. In cases involving payment diversion or authorised push payment fraud, her work is frequently the difference between recovery and total loss.",
        "Vivian supports the firm's significant experience in the private prosecution of fraud, corporate dishonesty and financial crime by converting that early tracing work into evidence that survives the transition from injunction to trial. She prepares exhibits, flow-of-funds schedules and expert reports, gives evidence where required, and works with counsel to present movement of money in a form that is immediately intelligible to a jury.",
        "Her work is inseparable from recovery. Vivian supports advice on the best means of retrieving assets linked to the offending by identifying the institutions holding value, the jurisdictions in which they sit and the disclosure routes available against each — evidence that regularly underpins proprietary and worldwide freezing orders, Bankers Trust and Norwich Pharmacal applications, and direct engagement with exchanges and payment providers holding frozen balances. She also quantifies loss for civil claims, insurance notification and confiscation.",
        "Alongside investigative work, Vivian advises clients on payment controls, supplier verification and authorisation processes, and on the detection measures that would have caught the transaction before it left.",
        "She is quick, extremely composed under pressure, and unusually good at explaining a complex funds trail to people who are hearing it for the first time. Clients frequently comment that she was the first person to make the situation feel manageable.",
      ],
      experience: [
        "Funds tracing completed within forty-eight hours of a seven-figure payment diversion fraud, supporting an emergency proprietary injunction",
        "Identification of layered transfers through multiple payment institutions and offshore accounts, leading to substantial recovery",
        "Flow-of-funds analysis and exhibits prepared for a Crown Court private prosecution of a former employee",
        "Tracing of proceeds converted into digital assets and subsequently returned to the regulated banking sector",
        "Loss quantification and evidential support for parallel civil proceedings and an insurance claim",
      ],
    },
    {
      slug: "chris-duman",
      name: "Chris Duman",
      shortName: "Chris Duman",
      initials: "CD",
      role: "Investigator",
      firm: "Edison Law",
      photo: "/images/people/chris-duman.png",
      photoWidth: 400,
      photoHeight: 560,
      summary:
        "Investigator in the financial crime team. Ground-level enquiry work that turns a suspicion into a set of established facts: locating people, confirming what they own, and establishing what they are actually doing.",
      bio: [
        "Chris is an investigator within the firm's financial crime team. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Chris's contribution is the ground-level enquiry work that turns a suspicion into a set of established facts.",
        "He works for companies, organisations and individuals who have been the victims of crime, and his focus is field investigation: locating people, confirming what they own, and establishing what they are actually doing rather than what they claim. Chris carries out subject tracing, address and occupancy confirmation, discreet observation where it is proportionate and lawfully justified, lifestyle and expenditure enquiries, and the physical verification work that turns a paper assumption into evidence — that the vehicle is there, that the property is occupied, that the trading address exists and that someone is at it.",
        "Chris supports the firm's significant experience in the private prosecution of fraud, corporate dishonesty and financial crime by producing material that will withstand challenge. Private prosecutions attract close scrutiny of how evidence was obtained, and Chris works accordingly: contemporaneous logs, continuity of exhibits, properly recorded witness contact and full unused material passed to the lawyers without editing. He is also experienced in approaching reluctant or nervous witnesses — former employees, suppliers, ex-partners of a defendant — and in obtaining usable statements from people who initially want nothing to do with the case.",
        "His work bears directly on recovery. Chris supports advice on the best means of retrieving assets linked to the offending by finding the assets and the people connected to them: company and land registry enquiries, identification of nominees, relatives and associated businesses, confirmation of high-value goods and vehicles, and locating defendants who have moved, changed name or left the jurisdiction. His findings frequently provide the practical detail that makes a freezing, search or enforcement application viable.",
        "He also assists with internal investigations, including site attendance, employee interviews and enquiries following whistleblower reports.",
        "Chris is straightforward, physically unremarkable in the way that field work requires, and very hard to put off. Colleagues note that he tends to come back with the answer, including when the answer is one nobody expected.",
      ],
      experience: [
        "Location of a defendant who had relocated and changed name, enabling service and subsequent enforcement",
        "Occupancy and lifestyle enquiries establishing a defendant's control of property held in a relative's name",
        "Witness enquiries producing three signed statements in a private prosecution where the client had assumed no witnesses were available",
        "Site attendance and document preservation following the discovery of an internal procurement fraud",
        "Verification of a supplier's trading address and operations, establishing it as a shell used to extract funds",
      ],
    },
  ],

  insights: [
    {
      slug: "tracing-assets-across-wallets",
      type: "Investigation note",
      date: "2026-08-18",
      dateLabel: "18.08.2026",
      title: "Tracing assets across multiple wallets: an evidence-first approach",
      description:
        "A practical overview of transaction mapping, evidence provenance and the legal decisions that follow.",
      related: ["crypto", "digital-assets"],
    },
    {
      slug: "hmrc-enquiry-evidence",
      type: "Legal explainer",
      date: "2026-07-09",
      dateLabel: "09.07.2026",
      title: "What an HMRC enquiry actually needs from the file",
      description:
        "How to separate the documents that decide a tax dispute from the volume that merely surrounds it.",
      related: ["tax"],
    },
    {
      slug: "preserving-digital-evidence",
      type: "Investigation note",
      date: "2026-06-12",
      dateLabel: "12.06.2026",
      title: "Preserving digital evidence before the legal route is chosen",
      description:
        "What to hold, what not to alter, and why early method matters more than early accusation.",
      related: ["financial-crime", "crypto"],
    },
  ],
};
