/**
 * Edison Law content. Turn development on or off in config.js.
 */
import { config } from "./config.js";

export const site = {
  mode: config.develop ? "development" : "production",
  canonicalOrigin: "https://edisonlaw.co.uk",
  name: "Edison Law",
  descriptor: "Law Firm · London",
  masterLine: "Following digital evidence. Building legal cases.",
  shortLine: "Editorial forensics for modern legal work.",
  lang: "en-GB",
  locale: "en_GB",
  themeColor: "#0A2028",
  backgroundColor: "#F1F6F4",
  sraNumber: "510498",
  sraUrl: "https://www.sra.org.uk/consumers/register/organisation/?sraNumber=510498",
  sraSince: "1 November 2015",
  email: "abi.wills@edisonlaw.co.uk",
  emailSource: "public directory — confirm before launch",
  phone: "",
  address: {
    line1: "12 Augustus Road",
    line2: "Wimbledon",
    city: "London",
    postcode: "SW19 6LN",
    country: "England",
  },
  analytics: { enabled: config.analytics },
  search: { enabled: config.search },

  nav: [
    { label: "Expertise", href: "/expertise/" },
    { label: "Insights", href: "/insights/" },
    { label: "People", href: "/people/" },
    { label: "About", href: "/about/" },
    { label: "Contact", href: "/contact/", kind: "button" },
  ],

  rail: [
    { label: "Expertise", href: "/expertise/" },
    { label: "Investigations", href: "/insights/" },
    { label: "Insights", href: "/insights/" },
    { label: "People", href: "/people/" },
    { label: "About", href: "/about/" },
    { label: "Contact", href: "/contact/" },
  ],

  footerLinks: [
    { label: "Legal & regulatory", href: "/legal-regulatory/" },
    { label: "Pricing", href: "/pricing/" },
    { label: "Complaints", href: "/complaints/" },
    { label: "Privacy", href: "/privacy/" },
    { label: "Cookies", href: "/cookies/" },
    { label: "Accessibility", href: "/accessibility/" },
    { label: "Fraud warning", href: "/fraud-warning/" },
  ],

  practices: [
    {
      id: "financial-crime",
      index: "01",
      title: "Financial crime",
      href: "/expertise/financial-crime/",
      summary: "Investigations, defence and advisory work where the facts sit across companies, accounts and people.",
    },
    {
      id: "tax",
      index: "02",
      title: "Tax disputes & resolution",
      href: "/expertise/tax-disputes-resolution/",
      summary: "HMRC enquiries, disclosure and settlement, and litigation support when the numbers and the law diverge.",
    },
    {
      id: "crypto",
      index: "03",
      title: "Crypto investigations",
      href: "/expertise/crypto-investigations/",
      summary: "Transaction analysis and evidence strategy for matters that begin on-chain and must end in a legal position.",
    },
    {
      id: "digital-assets",
      index: "04",
      title: "Digital asset disputes",
      href: "/expertise/digital-asset-disputes/",
      summary: "Ownership, control and recovery strategy for assets that exist as records rather than objects.",
    },
  ],

  people: [
    {
      slug: "zayn-marin",
      name: "Zayn Marin",
      shortName: "Zayn Marin",
      initials: "ZM",
      role: "Financial Forensic Expert",
      firm: "Edison Law",
      photo: "/images/people/zayn-marin.png",
      photoWidth: 472,
      photoHeight: 472,
      summary:
        "The firm's in-house financial forensic expert. Turns disordered financial material into evidence a court will accept, from first suspicion through trial, confiscation and recovery.",
      bio: [
        "Zayn is the firm's in-house financial forensic expert. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Zayn's role is the one that makes that record possible: he turns disordered financial material into evidence a court will accept.",
        "He works for companies, organisations and individuals who have been the victims of crime, and is usually involved from the first meeting onward. Where a client arrives with a suspicion, a gap in the accounts or an unexplained payment run, Zayn establishes what actually happened — reconstructing ledgers, unwinding intercompany transfers, rebuilding destroyed or manipulated records, quantifying loss and identifying the point at which money left the client's control and where it went next.",
        "Zayn supports the firm's significant experience in the private prosecution of fraud, corporate dishonesty and financial crime by building the financial spine of those cases. He prepares expert reports and schedules for use in the Crown Court, gives evidence at trial, and works closely with counsel to reduce complex financial narratives to something a jury can follow. He is equally comfortable being cross-examined on methodology as he is explaining it to a board that has never seen a forensic report before.",
        "His work is central to recovery. Zayn advises on the best means of retrieving assets linked to the offending by locating them first — tracing funds through bank records, corporate structures, nominee accounts, property transactions and digital wallets, and producing the evidence needed to support freezing, proprietary and disclosure applications at speed. He also quantifies benefit for the purposes of confiscation proceedings and prepares the loss analyses relied on in civil claims, insurance notifications and settlement negotiations.",
        "Alongside investigative work, Zayn advises on regulatory and remedial matters: transaction testing, reconstruction of accounting positions for reporting purposes, assessment of control failures, and the design of monitoring that will detect the same conduct if it recurs.",
        "Zayn is unusually good at the part most experts find difficult — saying clearly what the numbers do and do not prove. Clients value the fact that he will tell them early when a case is stronger than they feared, and just as early when it is not.",
      ],
      experience: [
        "Reconstruction of three years of manipulated management accounts, establishing the mechanism and quantum of a long-running invoicing fraud",
        "Tracing and quantification exercise underpinning an emergency worldwide freezing order",
        "Expert evidence at trial in a private prosecution of a former finance director",
        "Benefit and available amount analysis in confiscation proceedings following conviction",
        "Forensic review of a payments business's transaction records following the discovery of internal fraud",
      ],
    },
    {
      slug: "spencer-espinoza",
      name: "Spencer Espinoza",
      shortName: "Spencer Espinoza",
      initials: "SE",
      role: "Senior Solicitor — Fraud, Financial Crime & Private Prosecutions",
      firm: "Edison Law",
      photo: "/images/people/spencer-espinoza.png",
      photoWidth: 472,
      photoHeight: 472,
      summary:
        "Senior solicitor in the financial crime team. Runs some of the firm's largest and most document-heavy matters from first instruction through to verdict, usually brought in once a client has realised the problem is bigger than they first thought.",
      bio: [
        "Spencer is a senior solicitor in the firm's financial crime team. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Spencer runs some of the firm's largest and most document-heavy matters from first instruction through to verdict.",
        "He acts for companies, organisations and individuals who have been the victims of crime. His caseload covers senior management and boardroom fraud, false accounting, misappropriation of company funds, procurement and supplier fraud, shareholder disputes with a dishonesty element, and substantial losses suffered by private clients through misrepresented investments. Spencer is usually brought in at the point where a client has realised the problem is bigger than they first thought, and his first task is to impose order on it.",
        "Spencer contributes significantly to the firm's experience in the private prosecution of fraud, corporate dishonesty and financial crime. He conducts cases end to end — scoping the investigation, directing the firm's investigators and forensic experts, assembling the evidential file to a criminal standard, managing disclosure and unused material, instructing counsel and attending throughout trial. He is rigorous about the private prosecutor's duties of candour and disclosure, on the straightforward basis that a case brought sloppily will not survive the defence's first serious application.",
        "Asset recovery is integral to how he runs a matter. Spencer advises clients on the best means of retrieving assets linked to the offending, and settles recovery strategy at the outset rather than after conviction. He obtains urgent freezing, search and disclosure orders, coordinates restraint and confiscation with civil proprietary claims, and uses insolvency remedies where they reach the money faster. Where value has moved abroad, he manages foreign counsel and enforcement as part of a single strategy.",
        "He also advises boards on internal investigations, employee misconduct, whistleblowing complaints, regulatory notification and dealings with the FCA, SFO and police.",
        "Spencer is measured, decisive and notably good with clients under pressure. He supervises several of the firm's junior lawyers and is known internally for insisting that every file be capable of being picked up cold and understood by anyone in the team.",
      ],
      experience: [
        "Conduct of a private prosecution of two senior managers for a multi-year false invoicing scheme, resulting in conviction and confiscation",
        "Emergency freezing and search orders obtained within seventy-two hours of a fiduciary's misappropriation coming to light",
        "Parallel criminal, civil and insolvency proceedings pursued for a corporate client, achieving full recovery by settlement",
        "Board-level internal investigation into procurement irregularities, followed by dismissals and a regulatory report",
        "Recovery of funds and property transferred to family members in anticipation of enforcement",
      ],
    },
    {
      slug: "sofia-nowak",
      name: "Sofia Nowak",
      shortName: "Sofia Nowak",
      initials: "SN",
      role: "Associate Solicitor — Fraud, Financial Crime & Private Prosecutions",
      firm: "Edison Law",
      photo: "/images/people/sofia-nowak.png",
      photoWidth: 400,
      photoHeight: 560,
      summary:
        "Associate solicitor in the financial crime team. Closely involved in the day-to-day conduct of cases from first instruction through to trial, and often a client's principal point of contact.",
      bio: [
        "Sofia is an associate solicitor in the firm's financial crime team. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Sofia is closely involved in the day-to-day conduct of those cases, from first instruction through to trial.",
        "She acts for companies, organisations and individuals who have been the victims of crime. Her practice covers employee and fiduciary fraud, false accounting, misappropriation of company funds, supplier and invoicing fraud, and investment schemes affecting private individuals. Sofia is often a client's principal point of contact, and she is valued for keeping people properly informed in matters that are frequently distressing as well as complex.",
        "Sofia contributes to the firm's significant experience in the private prosecution of fraud, corporate dishonesty and financial crime. She prepares case papers to a criminal evidential standard, drafts witness statements, manages disclosure and unused material, instructs counsel and experts, and attends court throughout proceedings. She takes seriously the duties that attach to a private prosecutor — candour, disclosure and objectivity — and applies them rigorously, on the understanding that a case brought carelessly will not survive contact with the defence.",
        "She also works on asset recovery, assisting clients on the best means of retrieving assets linked to the offending. Sofia prepares applications for freezing, search and disclosure orders, works with forensic accountants and investigators on tracing exercises, and supports restraint and confiscation proceedings alongside civil and insolvency claims. Much of this work is done at short notice, and she is well suited to it.",
        "Sofia additionally advises on internal investigations and regulatory matters, including reporting obligations, employee interviews and the remedial steps that follow the discovery of misconduct.",
        "She is precise, extremely well organised and notably calm under pressure. Colleagues describe her as the person who has already found the document everyone else is still looking for.",
      ],
      experience: [
        "Preparation of the case file and disclosure schedules in a private prosecution of a former employee for a multi-year invoicing fraud",
        "Assisting on an urgent freezing and search order application following the discovery of fiduciary misappropriation",
        "Acting for individual investors in a collapsed investment scheme, coordinating tracing and civil recovery",
        "Supporting an internal investigation and subsequent report arising from suspected procurement fraud",
        "Preparation of witness evidence and trial bundles in Crown Court proceedings",
      ],
    },
    {
      slug: "eva-adelman",
      name: "Eva Adelman",
      shortName: "Eva Adelman",
      initials: "EA",
      role: "Equity Associate — Fraud, Financial Crime & Private Prosecutions",
      firm: "Edison Law",
      photo: "/images/people/eva-adelman.png",
      photoWidth: 400,
      photoHeight: 560,
      summary:
        "Equity associate in the financial crime team. Combines senior case conduct with a stake in how matters are chosen, resourced and run, and is the principal point of contact for a number of corporate clients.",
      bio: [
        "Eva is an equity associate in the firm's financial crime team, holding a stake in the practice she helps to build. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Eva combines the hands-on case conduct of a senior fee earner with a genuine ownership interest in how the firm's cases are chosen, resourced and run.",
        "She acts for companies, organisations and individuals who have been the victims of crime. Her practice covers corporate fraud and false accounting, misappropriation by directors and senior employees, shareholder and joint venture disputes with a dishonesty element, supplier and procurement fraud, and losses suffered by individuals through misrepresented investments. She runs her own caseload and is the principal point of contact for a number of the firm's corporate clients.",
        "Eva contributes substantially to the firm's significant experience in the private prosecution of fraud, corporate dishonesty and financial crime. She takes cases from initial assessment — advising realistically on merit, cost and the likelihood of recovery before a client commits — through investigation, charge and trial. She is meticulous about the obligations of a private prosecutor, particularly disclosure and the duty of candour, and prepares files on the assumption that every decision taken will later be examined by the defence and the court.",
        "Asset recovery is a defining part of her work. Eva advises clients on the best means of retrieving assets linked to the offending, coordinating criminal restraint and confiscation with civil freezing and proprietary relief, disclosure orders against banks and third parties, and enforcement against property and corporate interests. She works closely with the firm's forensic and investigative teams to ensure recovery strategy is settled at the outset rather than assembled after conviction.",
        "She also advises on internal investigations, whistleblowing complaints, regulatory reporting and the governance failures that fraud tends to expose.",
        "Eva is commercially minded and direct. Clients value the fact that she frames every decision in terms of outcome and cost, and that she is willing to advise against a course of action when the numbers do not support it.",
      ],
      experience: [
        "Conduct of a private prosecution of two directors for false accounting and misappropriation of company funds",
        "Freezing and disclosure orders obtained on short notice, followed by full recovery by negotiated settlement",
        "Acting for a corporate client in parallel criminal, civil and insolvency proceedings arising from supplier fraud",
        "Advising a board on an internal investigation into senior management expenses and subsequent dismissals",
        "Tracing and recovery of funds transferred to family members and connected companies ahead of enforcement",
      ],
    },
    {
      slug: "martin-horak",
      name: "Martin Horák",
      shortName: "Martin Horák",
      initials: "MH",
      role: "Financial Crime Investigator",
      firm: "Edison Law",
      photo: "/images/people/martin-horak.png",
      photoWidth: 472,
      photoHeight: 472,
      summary:
        "Financial crime investigator in the firm's team. Establishes what happened — who was involved, how the scheme operated and what evidence exists to prove it — with a particular focus on cross-border investigation.",
      bio: [
        "Martin is a financial crime investigator within the firm's team. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Martin's role is to establish what happened — who was involved, how the scheme operated and what evidence exists to prove it — before a case is committed to a strategy.",
        "He works for companies, organisations and individuals who have been the victims of crime, with a particular focus on cross-border investigation. Martin has spent much of his career working on matters spanning Central and Eastern Europe and the wider EU, and is experienced in obtaining information from foreign registries, court records, insolvency files, procurement databases and regulatory sources. He works comfortably in several languages, and is frequently the person who unlocks a case by reading the document nobody else could.",
        "Martin supports the firm's significant experience in the private prosecution of fraud, corporate dishonesty and financial crime by building case files that hold up under scrutiny. He identifies and approaches witnesses, takes statements, gathers and preserves documentary evidence, and maintains the continuity and disclosure records that a private prosecution demands. He is disciplined about method: everything logged, everything retained, nothing obtained in a way that will later embarrass the case.",
        "Much of his work is directed at recovery. Martin supports advice on the best means of retrieving assets linked to the offending by identifying the people and entities behind a fraud — nominee directors, connected companies, family members holding property, undisclosed relationships between insiders and suppliers — and by locating individuals who have moved abroad or gone deliberately to ground. His findings regularly provide the factual basis for freezing, disclosure and enforcement applications, and for service on defendants who assumed they could not be found.",
        "He also assists with internal investigations and regulatory matters, including employee interviews, whistleblower follow-up and enquiries in overseas subsidiaries.",
        "Martin is patient, persistent and quietly effective. Colleagues note that he rarely reports anything until he can prove it, and that he has a habit of producing the one document that changes the shape of a case.",
      ],
      experience: [
        "Investigation into a procurement fraud spanning three European jurisdictions, identifying undisclosed links between an internal manager and a supplier network",
        "Location of a defendant who had relocated abroad under a variant of his name, enabling service and enforcement",
        "Recovery of foreign registry and court records establishing a defendant's control of companies used to receive diverted funds",
        "Witness enquiries and statement-taking supporting a Crown Court private prosecution",
        "Enquiries within an overseas subsidiary following a whistleblower report of falsified invoicing",
      ],
    },
    {
      slug: "vivian-adler",
      name: "Vivian Adler",
      shortName: "Vivian Adler",
      initials: "VA",
      role: "Financial Forensic Expert",
      firm: "Edison Law",
      photo: "/images/people/vivian-adler.png",
      photoWidth: 472,
      photoHeight: 472,
      summary:
        "Financial forensic expert in the financial crime team. Specialises in rapid financial triage and payments tracing in the first hours of a matter, when the question is where the money is right now.",
      bio: [
        "Vivian is a financial forensic expert within the firm's financial crime team. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Vivian's particular strength is speed: she is the person the team turns to in the first hours of a matter, when the question is not yet how a fraud was built but where the money is right now.",
        "She works for companies, organisations and individuals who have been the victims of crime, and specialises in rapid financial triage and payments tracing. Working from incomplete records and under considerable time pressure, Vivian establishes the flow of funds out of a client's control — through payment service providers, correspondent banks, money service businesses, e-money accounts and digital asset platforms — and produces the evidenced picture needed to support an emergency application before the funds are dissipated further. In cases involving payment diversion or authorised push payment fraud, her work is frequently the difference between recovery and total loss.",
        "Vivian supports the firm's significant experience in the private prosecution of fraud, corporate dishonesty and financial crime by converting that early tracing work into evidence that survives the transition from injunction to trial. She prepares exhibits, flow-of-funds schedules and expert reports, gives evidence where required, and works with counsel to present movement of money in a form that is immediately intelligible to a jury.",
        "Her work is inseparable from recovery. Vivian supports advice on the best means of retrieving assets linked to the offending by identifying the institutions holding value, the jurisdictions in which they sit and the disclosure routes available against each — evidence that regularly underpins proprietary and worldwide freezing orders, Bankers Trust and Norwich Pharmacal applications, and direct engagement with exchanges and payment providers holding frozen balances. She also quantifies loss for civil claims, insurance notification and confiscation.",
        "Alongside investigative work, Vivian advises clients on payment controls, supplier verification and authorisation processes, and on the detection measures that would have caught the transaction before it left.",
        "She is quick, extremely composed under pressure, and unusually good at explaining a complex funds trail to people who are hearing it for the first time. Clients frequently comment that she was the first person to make the situation feel manageable.",
      ],
      experience: [
        "Funds tracing completed within forty-eight hours of a seven-figure payment diversion fraud, supporting an emergency proprietary injunction",
        "Identification of layered transfers through multiple payment institutions and offshore accounts, leading to substantial recovery",
        "Flow-of-funds analysis and exhibits prepared for a Crown Court private prosecution of a former employee",
        "Tracing of proceeds converted into digital assets and subsequently returned to the regulated banking sector",
        "Loss quantification and evidential support for parallel civil proceedings and an insurance claim",
      ],
    },
    {
      slug: "chris-duman",
      name: "Chris Duman",
      shortName: "Chris Duman",
      initials: "CD",
      role: "Solicitor — Fraud, Financial Crime & Private Prosecutions",
      firm: "Edison Law",
      photo: "/images/people/chris-duman.png",
      photoWidth: 400,
      photoHeight: 560,
      summary:
        "Solicitor in the financial crime team. Frequently the first person a client speaks to once a fraud surfaces: getting hold of a new matter fast, working out what can actually be achieved, and pushing it forward.",
      bio: [
        "Chris is a solicitor in the firm's financial crime team. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Chris's practice sits at the operational heart of it: getting hold of a new matter fast, working out what can actually be achieved, and pushing it forward.",
        "He acts for companies, organisations and individuals who have been the victims of crime — director and employee fraud, false accounting, misappropriation of company funds, supplier and procurement fraud, and individuals who have lost money through dishonest investment and advisory arrangements. Chris is frequently the first person a client speaks to once a fraud surfaces, and he gives a straight assessment at that point, including when the answer is unwelcome.",
        "He contributes to the firm's significant experience in the private prosecution of fraud, corporate dishonesty and financial crime. Chris prepares cases to a criminal evidential standard, manages disclosure and unused material, works alongside the firm's investigators and forensic experts, instructs counsel and attends throughout proceedings — always on the assumption that every step taken will be tested by the defence.",
        "Asset recovery runs through his work. Chris advises clients on the best means of retrieving assets linked to the offending, preparing urgent freezing, search and disclosure applications, supporting restraint and confiscation proceedings, and running parallel civil and insolvency claims where those reach the money faster.",
        "He also advises on internal investigations, employee misconduct, whistleblowing reports and regulatory notification.",
        "Chris is direct, tenacious and steady with clients who are anything but. Colleagues say he gets a chaotic new file into order quicker than anyone expects.",
      ],
      experience: [
        "Private prosecution of a former director for misappropriation of company funds",
        "Freezing and disclosure applications issued within days of a fraud being discovered",
        "Parallel criminal and civil claims for a corporate client arising from supplier fraud",
        "Internal investigation into senior employee expenses and false invoicing",
        "Recovery of funds transferred to connected parties ahead of enforcement",
      ],
    },
    {
      slug: "samuel-mor",
      name: "Samuel Mor",
      shortName: "Samuel Mor",
      initials: "SM",
      role: "Asset Tracing Specialist",
      firm: "Edison Law",
      photo: "/images/people/samuel-mor.png",
      photoWidth: 472,
      photoHeight: 472,
      summary:
        "Asset tracing specialist in the financial crime team. Locates recoverable value: where the money has gone, whether any of it is still there, and whether pursuing it is economically worthwhile.",
      bio: [
        "Samuel is an asset tracing specialist within the firm's financial crime team. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Samuel's role addresses the question every victim of fraud eventually asks: where has the money gone, and is any of it still there.",
        "He works for companies, organisations and individuals who have been the victims of crime, and his focus is locating recoverable value. Samuel follows funds from the point of loss through banking chains, payment institutions, corporate accounts and cross-border transfers, and identifies where proceeds have been converted — into property, vehicles, corporate interests, investments, luxury goods or digital assets — and in whose name they are now held. Where a defendant appears to be worth nothing, his job is to establish whether that is true or simply well arranged.",
        "Samuel supports the firm's significant experience in the private prosecution of fraud, corporate dishonesty and financial crime by producing tracing evidence that stands up in court as well as informing strategy. He prepares flow-of-funds schedules, asset registers and exhibits for use in criminal proceedings and in support of restraint and confiscation, and works with counsel to present the movement of money clearly and without overstatement.",
        "His work drives recovery decisions. Samuel supports advice on the best means of retrieving assets linked to the offending by establishing which assets exist, where they sit, who holds them and which jurisdiction's remedies apply. His findings underpin worldwide and proprietary freezing orders, disclosure orders against banks, exchanges and third parties, receivership applications and enforcement against real property and corporate holdings. He works with local counsel, registry researchers and investigators overseas, and is careful to assess not just whether an asset can be found but whether pursuing it is economically worthwhile.",
        "He also advises clients before litigation begins, assessing a counterparty's likely ability to satisfy a judgment so that money is not spent chasing a defendant with nothing behind him.",
        "Samuel is methodical, discreet and realistic. Clients value the fact that he will tell them early when there is value to pursue — and equally early when the trail ends.",
      ],
      experience: [
        "Tracing exercise across five jurisdictions establishing the destination of misappropriated group funds",
        "Identification of residential property held through a nominee, supporting a proprietary freezing order",
        "Asset register prepared in support of restraint and confiscation proceedings following conviction",
        "Location of investment holdings and corporate interests acquired with the proceeds of a long-running fraud",
        "Pre-action enforceability assessment that redirected a client's strategy toward a solvent third party",
      ],
    },
  ],

  insights: [
    {
      slug: "tracing-assets-across-wallets",
      type: "Investigation note",
      date: "2026-08-18",
      dateLabel: "18.08.2026",
      title: "Tracing assets across multiple wallets: an evidence-first approach",
      description:
        "A practical overview of transaction mapping, evidence provenance and the legal decisions that follow.",
      related: ["crypto", "digital-assets"],
    },
    {
      slug: "hmrc-enquiry-evidence",
      type: "Legal explainer",
      date: "2026-07-09",
      dateLabel: "09.07.2026",
      title: "What an HMRC enquiry actually needs from the file",
      description:
        "How to separate the documents that decide a tax dispute from the volume that merely surrounds it.",
      related: ["tax"],
    },
    {
      slug: "preserving-digital-evidence",
      type: "Investigation note",
      date: "2026-06-12",
      dateLabel: "12.06.2026",
      title: "Preserving digital evidence before the legal route is chosen",
      description:
        "What to hold, what not to alter, and why early method matters more than early accusation.",
      related: ["financial-crime", "crypto"],
    },
  ],
};
