/**
 * Edison Law content. Turn development on or off in config.js.
 */
import { config } from "./config.js";

export const site = {
  mode: config.develop ? "development" : "production",
  canonicalOrigin: "https://edisonlaw.co.uk",
  name: "Edison Law",
  descriptor: "Law Firm · London",
  masterLine: "When authorities decline to act, we deliver justice.",
  shortLine:
    "A specialist firm of solicitors and barristers for financial crime investigation, private prosecution and asset recovery.",
  lang: "en-GB",
  locale: "en_GB",
  themeColor: "#0A2028",
  backgroundColor: "#F1F6F4",
  sraNumber: "510498",
  sraUrl: "https://www.sra.org.uk/consumers/register/organisation/?sraNumber=510498",
  sraSince: "1 November 2015",
  email: "abi.wills@edisonlaw.co.uk",
  emailSource: "public directory — confirm before launch",
  phone: "",
  address: {
    line1: "12 Augustus Road",
    line2: "Wimbledon",
    city: "London",
    postcode: "SW19 6LN",
    country: "England",
  },
  analytics: { enabled: config.analytics },
  search: { enabled: config.search },

  nav: [
    { label: "Expertise", href: "/expertise/" },
    { label: "Investigations", href: "/investigations/" },
    { label: "Insights", href: "/insights/" },
    { label: "People", href: "/people/" },
    { label: "Join us", href: "/join-us/" },
    { label: "About", href: "/about/" },
    { label: "Contact", href: "/contact/", kind: "button" },
  ],

  rail: [
    { label: "Expertise", href: "/expertise/" },
    { label: "Investigations", href: "/investigations/" },
    { label: "Insights", href: "/insights/" },
    { label: "People", href: "/people/" },
    { label: "Join us", href: "/join-us/" },
    { label: "About", href: "/about/" },
    { label: "Contact", href: "/contact/" },
  ],

  footerLinks: [
    { label: "Legal & regulatory", href: "/legal-regulatory/" },
    { label: "Pricing", href: "/pricing/" },
    { label: "Complaints", href: "/complaints/" },
    { label: "Privacy", href: "/privacy/" },
    { label: "Cookies", href: "/cookies/" },
    { label: "Accessibility", href: "/accessibility/" },
    { label: "Fraud warning", href: "/fraud-warning/" },
  ],

  practices: [
    {
      id: "private-prosecutions",
      index: "01",
      title: "Private prosecutions",
      href: "/expertise/private-prosecutions/",
      summary:
        "When public authorities decline to investigate or prosecute, we offer an alternative route to justice — from investigation through to trial.",
    },
    {
      id: "asset-tracing",
      index: "02",
      title: "Asset tracing & recovery",
      href: "/expertise/asset-tracing-recovery/",
      summary:
        "We trace and recover misappropriated assets wherever they are concealed — offshore structures, wallets, shell companies or alter-ego entities.",
    },
    {
      id: "crypto-fraud",
      index: "03",
      title: "Crypto fraud & digital assets",
      href: "/expertise/crypto-fraud-digital-assets/",
      summary:
        "Legal expertise with blockchain analytics to trace stolen digital assets through complex transaction chains.",
    },
    {
      id: "regulatory",
      index: "04",
      title: "Regulatory defence & investigations",
      href: "/expertise/regulatory-defence-investigations/",
      summary:
        "Representation for individuals and corporates under investigation by the SFO, FCA, HMRC and other regulatory bodies.",
    },
    {
      id: "cross-border",
      index: "05",
      title: "Cross-border fraud & corruption",
      href: "/expertise/cross-border-fraud-corruption/",
      summary:
        "Multi-jurisdictional asset recovery, working with local counsel to secure evidence, freezing orders and judgment enforcement.",
    },
    {
      id: "corporate-intelligence",
      index: "06",
      title: "Corporate intelligence & pre-litigation",
      href: "/expertise/corporate-intelligence/",
      summary:
        "Confidential due diligence, background investigations and integrity monitoring before high-value transactions and appointments.",
    },
  ],

  investigations: [
    {
      id: "internal",
      copyKey: "internalInvestigations",
      title: "Internal investigations",
      href: "/investigations/internal-investigations/",
      summary:
        "Board-level, employee and whistleblower enquiries run so the file still holds if you later prosecute, report or litigate.",
      related: ["regulatory"],
    },
    {
      id: "financial-crime",
      copyKey: "financialCrimeInvestigations",
      title: "Financial crime investigations",
      href: "/investigations/financial-crime/",
      summary:
        "Who was involved, how the scheme ran, and what the documents actually prove — before anyone is asked to commit to a legal route.",
      related: ["private-prosecutions"],
    },
    {
      id: "digital",
      copyKey: "digitalInvestigations",
      title: "Digital and payments investigations",
      href: "/investigations/digital-crypto/",
      summary:
        "Payment diversion, authorised push payment fraud, wallets and devices: hold the trail, then map it in a form a court will accept.",
      related: ["crypto-fraud", "private-prosecutions"],
    },
    {
      id: "cross-border",
      copyKey: "crossBorderInvestigations",
      title: "Cross-border investigations",
      href: "/investigations/cross-border/",
      summary:
        "Foreign registries, overseas subsidiaries, and people who have moved or gone to ground. The facts do not stop at the UK border.",
      related: ["cross-border"],
    },
    {
      id: "asset-tracing",
      copyKey: "assetTracingInvestigations",
      title: "Asset tracing investigations",
      href: "/investigations/asset-tracing/",
      summary:
        "Where the money went, whether any of it is still there, and whether pursuing it is economically worthwhile.",
      related: ["asset-tracing", "crypto-fraud"],
    },
  ],

  people: [
    {
      slug: "zayn-marin",
      name: "Zayn Marin",
      shortName: "Zayn Marin",
      initials: "ZM",
      role: "Financial Forensic Expert",
      firm: "Edison Law",
      photo: "/images/people/zayn-marin.png",
      photoWidth: 472,
      photoHeight: 472,
      summary:
        "The firm's in-house financial forensic expert. Turns disordered financial material into evidence a court will accept.",
      bio: [
        "Zayn is the firm's in-house financial forensic expert. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Zayn's role is to turn disordered financial material into evidence a court will accept.",
        "He works for companies, organisations and individuals who have been the victims of crime, usually from the first meeting. Where a client arrives with a suspicion, a gap in the accounts or an unexplained payment run, he reconstructs ledgers, unwinds transfers, quantifies loss and identifies where the money went next.",
        "He builds the financial spine of private prosecutions: expert reports and schedules for the Crown Court, evidence at trial, and a narrative a jury can follow. Recovery sits in the same work — tracing through banks, nominees, property and wallets, and quantifying benefit for confiscation, civil claims and insurance.",
        "Zayn is unusually clear about what the numbers do and do not prove. Clients are told early when a case is stronger than they feared, and just as early when it is not.",
      ],
      experience: [
        "Reconstruction of three years of manipulated management accounts in a long-running invoicing fraud",
        "Tracing and quantification underpinning an emergency worldwide freezing order",
        "Expert evidence at trial in a private prosecution of a former finance director",
        "Benefit and available-amount analysis in confiscation following conviction",
      ],
    },
    {
      slug: "spencer-espinoza",
      name: "Spencer Espinoza",
      shortName: "Spencer Espinoza",
      initials: "SE",
      role: "Senior Solicitor — Fraud, Financial Crime & Private Prosecutions",
      firm: "Edison Law",
      photo: "/images/people/spencer-espinoza.png",
      photoWidth: 472,
      photoHeight: 472,
      summary:
        "Senior solicitor in the financial crime team. Runs large, document-heavy matters from first instruction through to verdict.",
      bio: [
        "Spencer is a senior solicitor in the firm's financial crime team. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Spencer runs some of the firm's largest and most document-heavy matters from first instruction through to verdict.",
        "He acts for companies, organisations and individuals who have been the victims of crime: boardroom and senior-management fraud, false accounting, misappropriation, procurement fraud, and losses through misrepresented investments. He is usually brought in once the problem is bigger than first thought, and his first task is to impose order on it.",
        "He conducts private prosecutions end to end — investigation, a criminal-standard file, disclosure, counsel and trial — on the basis that a sloppy case will not survive the defence. Recovery is settled at the outset: freezing, search and disclosure, restraint and confiscation, civil claims and insolvency where they reach the money faster.",
        "Spencer is measured, decisive and good with clients under pressure. He supervises junior lawyers and insists every file can be picked up cold and understood.",
      ],
      experience: [
        "Private prosecution of two senior managers for a multi-year false invoicing scheme, with conviction and confiscation",
        "Emergency freezing and search orders within seventy-two hours of a fiduciary's misappropriation",
        "Parallel criminal, civil and insolvency proceedings for a corporate client, settled with recovery",
        "Board-level internal investigation into procurement irregularities, with dismissals and a regulatory report",
      ],
    },
    {
      slug: "sofia-nowak",
      name: "Sofia Nowak",
      shortName: "Sofia Nowak",
      initials: "SN",
      role: "Associate Solicitor — Fraud, Financial Crime & Private Prosecutions",
      firm: "Edison Law",
      photo: "/images/people/sofia-nowak.png",
      photoWidth: 400,
      photoHeight: 560,
      summary:
        "Associate solicitor in the financial crime team. Day-to-day conduct of cases from first instruction through to trial, and often the client's principal point of contact.",
      bio: [
        "Sofia is an associate solicitor in the firm's financial crime team. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Sofia is closely involved in the day-to-day conduct of those cases, from first instruction through to trial.",
        "She acts for companies, organisations and individuals who have been the victims of crime: employee and fiduciary fraud, false accounting, misappropriation, supplier fraud and investment schemes affecting private individuals. She is often the client's principal point of contact in matters that are distressing as well as complex.",
        "She prepares case papers to a criminal evidential standard, drafts statements, manages disclosure, instructs counsel and attends court. Recovery work sits alongside: freezing, search and disclosure applications, tracing with forensic colleagues, and restraint, confiscation and civil claims at short notice.",
        "Sofia is precise, well organised and calm under pressure. Colleagues describe her as the person who has already found the document everyone else is still looking for.",
      ],
      experience: [
        "Case file and disclosure schedules in a private prosecution of a former employee for invoicing fraud",
        "Urgent freezing and search order following fiduciary misappropriation",
        "Acting for investors in a collapsed scheme, coordinating tracing and civil recovery",
        "Witness evidence and trial bundles in Crown Court proceedings",
      ],
    },
    {
      slug: "eva-adelman",
      name: "Eva Adelman",
      shortName: "Eva Adelman",
      initials: "EA",
      role: "Equity Associate — Fraud, Financial Crime & Private Prosecutions",
      firm: "Edison Law",
      photo: "/images/people/eva-adelman.png",
      photoWidth: 400,
      photoHeight: 560,
      summary:
        "Equity associate in the financial crime team. Senior case conduct with a stake in how matters are chosen, resourced and run.",
      bio: [
        "Eva is an equity associate in the firm's financial crime team, holding a stake in the practice she helps to build. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Eva combines senior case conduct with a say in how matters are chosen, resourced and run.",
        "She acts for companies, organisations and individuals who have been the victims of crime: corporate fraud, misappropriation by directors, shareholder disputes with a dishonesty element, procurement fraud and misrepresented investments. She runs her own caseload and is the principal contact for a number of corporate clients.",
        "She takes cases from merit and cost assessment through investigation, charge and trial, on the assumption that every decision will be examined by the defence. Recovery is settled at the outset: restraint and confiscation with civil freezing, disclosure against banks, and enforcement against property and companies.",
        "Eva is commercially minded and direct. She frames decisions in terms of outcome and cost, and will advise against a course the numbers do not support.",
      ],
      experience: [
        "Private prosecution of two directors for false accounting and misappropriation of company funds",
        "Freezing and disclosure orders on short notice, followed by recovery by settlement",
        "Parallel criminal, civil and insolvency proceedings arising from supplier fraud",
        "Board advice on an internal investigation into senior management expenses and dismissals",
      ],
    },
    {
      slug: "martin-horak",
      name: "Martin Horák",
      shortName: "Martin Horák",
      initials: "MH",
      role: "Financial Crime Investigator",
      firm: "Edison Law",
      photo: "/images/people/martin-horak.png",
      photoWidth: 472,
      photoHeight: 472,
      summary:
        "Financial crime investigator in the firm's team. Establishes what happened, with a particular focus on cross-border enquiry.",
      bio: [
        "Martin is a financial crime investigator within the firm's team. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Martin's role is to establish what happened — who was involved, how the scheme operated, and what evidence exists to prove it — before a strategy is chosen.",
        "He works for companies, organisations and individuals who have been the victims of crime, with a focus on cross-border investigation. He has spent much of his career on matters spanning Central and Eastern Europe and the wider EU: foreign registries, court records, insolvency files and procurement databases, often in several languages.",
        "He builds files that hold up: witnesses, statements, continuity and disclosure. Recovery work is the same method — nominee directors, connected companies, family members holding property, and people who have moved or gone to ground — so freezing, service and enforcement have facts underneath them.",
        "Martin is patient and quietly effective. He rarely reports anything until he can prove it, and he has a habit of producing the one document that changes the shape of a case.",
      ],
      experience: [
        "Procurement fraud spanning three European jurisdictions, identifying links between a manager and a supplier network",
        "Location of a defendant who had relocated abroad under a variant of his name",
        "Foreign registry and court records establishing control of companies used to receive diverted funds",
        "Witness enquiries and statements supporting a Crown Court private prosecution",
      ],
    },
    {
      slug: "vivian-adler",
      name: "Vivian Adler",
      shortName: "Vivian Adler",
      initials: "VA",
      role: "Financial Forensic Expert",
      firm: "Edison Law",
      photo: "/images/people/vivian-adler.png",
      photoWidth: 472,
      photoHeight: 472,
      summary:
        "Financial forensic expert in the financial crime team. Rapid financial triage and payments tracing in the first hours, when the question is where the money is now.",
      bio: [
        "Vivian is a financial forensic expert within the firm's financial crime team. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Vivian's particular strength is speed: the first hours of a matter, when the question is not yet how a fraud was built but where the money is right now.",
        "She works for companies, organisations and individuals who have been the victims of crime. From incomplete records she maps funds out through payment providers, correspondent banks, e-money accounts and digital-asset platforms, and produces the picture needed for an emergency application before value dissipates further.",
        "That early tracing becomes evidence that survives from injunction to trial: exhibits, flow-of-funds schedules and reports a jury can follow. She identifies the institutions holding value and the disclosure routes against each, and quantifies loss for civil claims, insurance and confiscation.",
        "She is quick, composed under pressure, and good at explaining a funds trail to people hearing it for the first time. Clients often say she was the first person to make the situation feel manageable.",
      ],
      experience: [
        "Funds tracing within forty-eight hours of a payment diversion, supporting an emergency proprietary injunction",
        "Layered transfers through payment institutions and offshore accounts, leading to recovery",
        "Flow-of-funds exhibits for a Crown Court private prosecution of a former employee",
        "Tracing of proceeds converted into digital assets and returned to the regulated banking sector",
      ],
    },
    {
      slug: "chris-duman",
      name: "Chris Duman",
      shortName: "Chris Duman",
      initials: "CD",
      role: "Solicitor — Fraud, Financial Crime & Private Prosecutions",
      firm: "Edison Law",
      photo: "/images/people/chris-duman.png",
      photoWidth: 400,
      photoHeight: 560,
      summary:
        "Solicitor in the financial crime team. Often the first person a client speaks to once a fraud surfaces: get hold of the matter, say what can be achieved, push it forward.",
      bio: [
        "Chris is a solicitor in the firm's financial crime team. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Chris's practice sits at the operational heart of it: getting hold of a new matter fast, working out what can actually be achieved, and pushing it forward.",
        "He acts for companies, organisations and individuals who have been the victims of crime — director and employee fraud, false accounting, misappropriation, supplier fraud, and losses through dishonest investment arrangements. He is frequently the first person a client speaks to, and he gives a straight assessment, including when the answer is unwelcome.",
        "He prepares cases to a criminal evidential standard, manages disclosure, works with investigators and forensic experts, and attends throughout proceedings. Recovery runs through the same file: urgent freezing, search and disclosure, restraint and confiscation, and civil or insolvency claims where they reach the money faster.",
        "Chris is direct, tenacious and steady with clients who are anything but. Colleagues say he gets a chaotic new file into order quicker than anyone expects.",
      ],
      experience: [
        "Private prosecution of a former director for misappropriation of company funds",
        "Freezing and disclosure applications issued within days of a fraud being discovered",
        "Parallel criminal and civil claims arising from supplier fraud",
        "Internal investigation into senior employee expenses and false invoicing",
      ],
    },
    {
      slug: "samuel-mor",
      name: "Samuel Mor",
      shortName: "Samuel Mor",
      initials: "SM",
      role: "Asset Tracing Specialist",
      firm: "Edison Law",
      photo: "/images/people/samuel-mor.png",
      photoWidth: 472,
      photoHeight: 472,
      summary:
        "Asset tracing specialist in the financial crime team. Locates recoverable value and says, early, whether pursuing it is worth the cost.",
      bio: [
        "Samuel is an asset tracing specialist within the firm's financial crime team. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Samuel's role addresses the question every victim of fraud eventually asks: where has the money gone, and is any of it still there.",
        "He works for companies, organisations and individuals who have been the victims of crime. He follows funds from the point of loss through banks, payment institutions and corporate accounts, and identifies where proceeds have been converted — property, vehicles, investments, goods or digital assets — and in whose name they are held. Where a defendant appears to be worth nothing, he tests whether that is true.",
        "He produces tracing evidence that stands up in court: flow-of-funds schedules, asset registers and exhibits for restraint, confiscation and freezing. He assesses not only whether an asset can be found but whether pursuing it is economically worthwhile, including before litigation begins.",
        "Samuel is methodical, discreet and realistic. Clients are told early when there is value to pursue — and equally early when the trail ends.",
      ],
      experience: [
        "Tracing exercise across five jurisdictions establishing the destination of misappropriated group funds",
        "Identification of residential property held through a nominee, supporting a proprietary freezing order",
        "Asset register prepared for restraint and confiscation following conviction",
        "Pre-action enforceability assessment that redirected strategy toward a solvent third party",
      ],
    },
    {
      slug: "callum-reeve",
      name: "Callum Reeve",
      shortName: "Callum Reeve",
      initials: "CR",
      role: "Confiscation Specialist",
      firm: "Edison Law",
      photo: "/images/people/callum-reeve.png",
      photoWidth: 400,
      photoHeight: 560,
      summary:
        "Confiscation specialist in the financial crime team. Turns a conviction or a settlement into a recoverable amount: benefit, available assets, and the orders that actually reach them.",
      bio: [
        "Callum is a confiscation specialist in the firm's financial crime team. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Callum's job is the part that comes after the verdict: making sure the benefit figure, the available amount and the enforcement route are ready before anyone assumes the money will come back.",
        "He acts for companies, organisations and individuals who have been the victims of crime. He prepares confiscation and compensation files, tests what a defendant actually owns, and works with tracing and forensic colleagues so hidden value is on the schedule rather than discovered too late.",
        "Callum supports advice on the best means of retrieving assets linked to the offending by coordinating restraint, confiscation and civil enforcement as one sequence, not three afterthoughts. He is precise about what POCA will reach and what it will not.",
        "He is calm, exact and unwilling to inflate a figure that will not survive a hearing. Clients are told the recoverable position, not the hopeful one.",
      ],
      experience: [
        "Benefit and available-amount analysis following conviction in a private prosecution of a finance director",
        "Restraint varied after hidden property and nominee holdings were identified",
        "Compensation schedule prepared alongside confiscation so the victim's claim was not left to the end",
        "Enforcement against assets transferred to family members ahead of sentencing",
      ],
    },
    {
      slug: "jonathan-pell",
      name: "Jonathan Pell",
      shortName: "Jonathan Pell",
      initials: "JP",
      role: "Forensic Accountant",
      firm: "Edison Law",
      photo: "/images/people/jonathan-pell.png",
      photoWidth: 472,
      photoHeight: 472,
      summary:
        "Forensic accountant in the financial crime team. Rebuilds the books, states what the numbers prove, and writes reports that can be cross-examined.",
      bio: [
        "Jonathan is a forensic accountant in the firm's financial crime team. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Jonathan's role is to turn disordered accounts into a financial narrative a court can follow.",
        "He acts for companies, organisations and individuals who have been the victims of crime. He reconstructs ledgers, unwinds intercompany transfers, quantifies loss and identifies the point at which money left the client's control. He will say, early, when the records do not support the allegation.",
        "His reports and schedules are written for trial, confiscation and civil recovery. He works with counsel on the figures that will actually be tested, and with investigators on the documents those figures need.",
        "Jonathan is measured and difficult to rush. Colleagues bring him the file when the story is bigger than the evidence.",
      ],
      experience: [
        "Reconstruction of manipulated management accounts establishing the mechanism of a long-running invoicing fraud",
        "Loss quantification supporting an emergency proprietary injunction",
        "Expert report and schedules prepared for a Crown Court private prosecution",
        "Transaction testing after internal fraud in a payments business",
      ],
    },
    {
      slug: "claire-benning",
      name: "Claire Benning",
      shortName: "Claire Benning",
      initials: "CB",
      role: "Corporate Intelligence Analyst",
      firm: "Edison Law",
      photo: "/images/people/claire-benning.png",
      photoWidth: 472,
      photoHeight: 472,
      summary:
        "Corporate intelligence analyst in the financial crime team. Establishes who a counterparty is, what they own, and whether a claim against them is worth the cost — before money is spent.",
      bio: [
        "Claire is a corporate intelligence analyst in the firm's financial crime team. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Claire's work sits before the first letter: who the other side actually is, and whether they can satisfy a judgment.",
        "She acts for companies, organisations and individuals who have been the victims of crime, and for boards instructing enhanced due diligence before a transaction, appointment or investment. She maps undisclosed litigation, connected companies, political exposure and assets held through nominees.",
        "Her findings inform recovery strategy as much as they inform whether to proceed at all. Claire is careful about method: open-source and registry work first, visible steps only on instruction.",
        "She is discreet, thorough and unwilling to overstate a connection she cannot prove. Clients value a short answer when the trail is thin.",
      ],
      experience: [
        "Pre-action intelligence on a counterparty showing the judgment would not be worth enforcing",
        "Mapping of connected companies and family holdings used to receive diverted funds",
        "Source-of-wealth review before a high-value appointment",
        "Integrity report supporting an internal investigation into a joint-venture partner",
      ],
    },
    {
      slug: "freya-lindqvist",
      name: "Freya Lindqvist",
      shortName: "Freya Lindqvist",
      initials: "FL",
      role: "Digital Forensics Analyst",
      firm: "Edison Law",
      photo: "/images/people/freya-lindqvist.png",
      photoWidth: 472,
      photoHeight: 472,
      summary:
        "Digital forensics analyst in the financial crime team. Preserves devices, mailboxes and logs so the digital record still exists when the legal route is chosen.",
      bio: [
        "Freya is a digital forensics analyst in the firm's financial crime team. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Freya's first task is preservation: hold the device, the mailbox and the log before anyone tidies the file.",
        "She acts for companies, organisations and individuals who have been the victims of crime. She images machines, captures accounts, records access, and produces exhibits with continuity intact. She will stop a well-meaning export that would destroy metadata.",
        "Her work feeds both investigation and recovery: payment records, deleted mail, device histories that show who moved what, and when. She writes method so it can be explained later, including under cross-examination.",
        "Freya is exact, quiet and difficult to fluster. The team calls her before anyone logs in.",
      ],
      experience: [
        "Imaging of laptops and phones in the first day of an internal fraud, before accounts were reset",
        "Mailbox preservation supporting a private prosecution of a former employee",
        "Continuity records for digital evidence used on an urgent search order",
        "Recovery of deleted payment instructions showing a supplier diversion",
      ],
    },
    {
      slug: "emily-croft",
      name: "Emily Croft",
      shortName: "Emily Croft",
      initials: "EC",
      role: "Solicitor — Restraint & Freezing",
      firm: "Edison Law",
      photo: "/images/people/emily-croft.png",
      photoWidth: 472,
      photoHeight: 472,
      summary:
        "Solicitor in the financial crime team, focused on restraint and freezing. Gets the order that stops the money moving, then keeps it in place.",
      bio: [
        "Emily is a solicitor in the firm's financial crime team, with a practice in restraint and freezing. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Emily is instructed when value is still moving and a delay will cost the client the asset.",
        "She acts for companies, organisations and individuals who have been the victims of crime. She prepares worldwide and proprietary freezing applications, Bankers Trust and Norwich Pharmacal orders, and the evidence packs those applications require — often on very short notice.",
        "Asset recovery is the point of the work, not a sequel. Emily coordinates with tracing and forensic colleagues so the order names the right institutions, and she manages the undertakings and variations that follow.",
        "She is organised, direct with clients under pressure, and careful not to ask a court for more than the evidence will carry.",
      ],
      experience: [
        "Worldwide freezing order obtained within days of a fiduciary's misappropriation coming to light",
        "Proprietary injunction supported by a forty-eight-hour payments-tracing picture",
        "Disclosure orders against banks holding diverted balances",
        "Variation and enforcement of a freezing order after assets were moved into a nominee's name",
      ],
    },
    {
      slug: "alistair-keene",
      name: "Alistair Keene",
      shortName: "Alistair Keene",
      initials: "AK",
      role: "Financial Crime Investigator",
      firm: "Edison Law",
      photo: "/images/people/alistair-keene.png",
      photoWidth: 472,
      photoHeight: 472,
      summary:
        "Financial crime investigator in the firm's team. Finds the people, the witnesses and the documents that turn a suspicion into a file.",
      bio: [
        "Alistair is a financial crime investigator within the firm's team. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Alistair's role is to establish who did what — and to put that in a form that will hold up.",
        "He acts for companies, organisations and individuals who have been the victims of crime. He identifies witnesses, takes statements, gathers documents and maintains continuity. He locates people who have moved, changed name, or gone to ground, including for service.",
        "Much of his work is directed at recovery: the connected supplier, the family member holding property, the person who can be found. Findings are logged so they can be disclosed without embarrassment.",
        "Alistair is patient and persistent. He reports when he can prove it, not when the story is interesting.",
      ],
      experience: [
        "Witness statements and unused-material records supporting a Crown Court private prosecution",
        "Location of a defendant who had left the jurisdiction under a variant of his name",
        "Enquiries establishing undisclosed links between an internal manager and a supplier",
        "Employee interviews following a whistleblower report of falsified invoicing",
      ],
    },
    {
      slug: "elena-costa",
      name: "Elena Costa",
      shortName: "Elena Costa",
      initials: "EC",
      role: "Payments Tracing Specialist",
      firm: "Edison Law",
      photo: "/images/people/elena-costa.png",
      photoWidth: 472,
      photoHeight: 472,
      summary:
        "Payments tracing specialist in the financial crime team. Follows diverted funds through banks, PSPs and e-money accounts in the first hours of a matter.",
      bio: [
        "Elena is a payments tracing specialist in the firm's financial crime team. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Elena is brought in when the question is where a payment went — today, not next month.",
        "She acts for companies, organisations and individuals who have been the victims of crime, particularly payment diversion and authorised push payment fraud. Working from incomplete references, she maps movement through correspondent banks, payment institutions and e-money accounts, and produces the picture needed for an emergency application.",
        "That early tracing becomes evidence: flow-of-funds schedules, institution lists, and the disclosure routes against each. She will say when the trail has left the regulated system, and when it has not.",
        "Elena is quick, clear with clients hearing the facts for the first time, and strict about not sending anyone back into an account that should be preserved.",
      ],
      experience: [
        "Payments map completed within two days of a seven-figure diversion, supporting a proprietary injunction",
        "Identification of layered transfers through multiple payment institutions",
        "Exhibits prepared for a private prosecution of a former employee who altered payee details",
        "Loss schedule for parallel civil proceedings and an insurance notification",
      ],
    },
    {
      slug: "daniel-harrow",
      name: "Daniel Harrow",
      shortName: "Daniel Harrow",
      initials: "DH",
      role: "Senior Asset Recovery Specialist",
      firm: "Edison Law",
      photo: "/images/people/daniel-harrow.png",
      photoWidth: 400,
      photoHeight: 560,
      summary:
        "Senior asset recovery specialist in the financial crime team. Decides which assets are worth reaching, in which order, and by which remedy.",
      bio: [
        "Daniel is a senior asset recovery specialist in the firm's financial crime team. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Daniel holds the recovery strategy: which asset, which court, which order, and at what cost.",
        "He acts for companies, organisations and individuals who have been the victims of crime. He works from tracing and intelligence already in hand, then sequences freezing, disclosure, receivership and enforcement so effort is not spent on value that cannot be reached.",
        "He coordinates local counsel overseas, insolvency routes where they are faster, and the difference between an asset that exists and an asset that can be sold. He will advise against a chase that will cost more than it returns.",
        "Daniel is commercial and unsentimental. Clients get a plan, and they get told when the plan should stop.",
      ],
      experience: [
        "Recovery strategy combining a proprietary freeze, disclosure against banks and later receivership",
        "Enforcement against property held through a nominee after tracing identified the true controller",
        "Insolvency route used to reach assets faster than a free-standing claim",
        "Decision to abandon overseas enforcement where the cost exceeded likely recovery",
      ],
    },
    {
      slug: "hugo-marchetti",
      name: "Hugo Marchetti",
      shortName: "Hugo Marchetti",
      initials: "HM",
      role: "Civil Recovery Solicitor",
      firm: "Edison Law",
      photo: "/images/people/hugo-marchetti.png",
      photoWidth: 472,
      photoHeight: 472,
      summary:
        "Civil recovery solicitor in the financial crime team. Runs the civil claim that reaches the money when a prosecution is not the fastest route, or when it runs in parallel.",
      bio: [
        "Hugo is a civil recovery solicitor in the firm's financial crime team. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Hugo's practice is the civil side of that work: proprietary claims, deceit, knowing receipt and the injunctions that hold value while the claim proceeds.",
        "He acts for companies, organisations and individuals who have been the victims of crime. He is often instructed alongside a criminal file, so the civil claim and the prosecution are one strategy rather than two firms writing past each other.",
        "He prepares freezing and disclosure applications, pleadings that match the evidential file, and settlement positions that reflect what can actually be recovered. He takes the duties of candour on without-notice applications as seriously as the result.",
        "Hugo is sharp, well organised and comfortable explaining a dual-track strategy to a client who has never seen one. He does not dress a weak civil claim as a second prosecution.",
      ],
      experience: [
        "Proprietary claim and freezing order run in parallel with a private prosecution of two directors",
        "Knowing-receipt claim against a company that received diverted supplier payments",
        "Without-notice disclosure application against a bank holding converted proceeds",
        "Settlement of a civil recovery after tracing showed the remaining value sat in reachable property",
      ],
    },
    {
      slug: "adam-brenner",
      name: "Adam Brenner",
      shortName: "Adam Brenner",
      initials: "AB",
      role: "Crypto Tracing Analyst",
      firm: "Edison Law",
      photo: "/images/people/adam-brenner.png",
      photoWidth: 472,
      photoHeight: 472,
      summary:
        "Crypto tracing analyst in the financial crime team. Maps wallets, exchanges and cash-outs, and states what on-chain data can and cannot prove.",
      bio: [
        "Adam is a crypto tracing analyst in the firm's financial crime team. We are a unique firm of solicitors and barristers with an unrivalled track record in conducting major fraud prosecutions and regulatory work, and Adam maps where digital value went — through wallets, mixers, bridges and exchanges — without pretending the chain shows more than it does.",
        "He acts for companies, organisations and individuals who have been the victims of crime, including wallet theft, investment scams and conversion of diverted fiat into digital assets. He produces clustering, hop maps and exchange-attribution that can be exhibited, and he flags when a hop is inference rather than fact.",
        "His work supports emergency applications against exchanges and the later trial file. He liaises on freeze requests and writes the limits of the tracing into the report, so counsel is not surprised in court.",
        "Adam is precise and unimpressed by theatre. He will say when the coins have cashed out, and when they have not.",
      ],
      experience: [
        "Wallet mapping supporting an emergency freeze request to a regulated exchange",
        "Tracing of proceeds converted from a payment diversion into digital assets and back into banking",
        "Exhibits for a private prosecution involving an unregulated trading platform",
        "Attribution report distinguishing confirmed exchange deposits from inferred clustering",
      ],
    },
  ],

  insights: [
    {
      slug: "tracing-assets-across-wallets",
      type: "Investigation note",
      date: "2026-08-18",
      dateLabel: "18.08.2026",
      title: "Tracing assets across multiple wallets: an evidence-first approach",
      description:
        "A practical overview of transaction mapping, evidence provenance and the legal decisions that follow.",
      related: ["crypto-fraud", "asset-tracing"],
    },
    {
      slug: "hmrc-enquiry-evidence",
      type: "Legal explainer",
      date: "2026-07-09",
      dateLabel: "09.07.2026",
      title: "What an HMRC enquiry actually needs from the file",
      description:
        "How to separate the documents that decide a tax dispute from the volume that merely surrounds it.",
      related: ["regulatory"],
    },
    {
      slug: "preserving-digital-evidence",
      type: "Investigation note",
      date: "2026-06-12",
      dateLabel: "12.06.2026",
      title: "Preserving digital evidence before the legal route is chosen",
      description:
        "What to hold, what not to alter, and why early method matters more than early accusation.",
      related: ["private-prosecutions", "crypto-fraud"],
    },
  ],
};
