export const people = [
  {
    slug: "richard-edison",
    name: "Richard Edison",
    shortName: "Richard Edison",
    initials: "RE",
    role: "Owner",
    firm: "Edison Law",
    principal: true,
    featured: true,
    photo: "/images/people/richard-edison.png",
    photoWidth: 570,
    photoHeight: 380,
    practicePhoto: "/images/people/richard-edison-practice.png",
    practicePhotoWidth: 626,
    practicePhotoHeight: 417,
    summary:
      "Owner of Edison Law. Holds the practice: the work, the people, and the files.",
    bio: [
      "Richard Edison is the owner of Edison Law. The practice is an SRA-regulated solicitors' firm in London for financial crime investigation, private prosecution and asset recovery.",
      "He holds the practice. The people who work the file sit here: lawyers, investigators and forensic specialists, on the same matters, from first instruction through to trial or a decision that no further step is justified.",
      "The work is legal-led investigation. Devices, accounts and originals are held before anyone drafts a narrative. A route is chosen only when the facts will carry it — a private prosecution, a freezing application, a civil claim, a report, or no further step.",
      "Confirm office, people and authorisation on the public SRA record if anything on this site might be out of date. Richard does not promise a recovery the facts cannot carry.",
    ],
  },
  {
    slug: "anjali-mehta",
    name: "Anjali Mehta",
    shortName: "Anjali Mehta",
    initials: "AM",
    role: "Financial Forensic Expert",
    firm: "Edison Law",
    featured: true,
    photo: "/images/people/anjali-mehta.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "The firm's in-house financial forensic expert. Turns disordered financial material into evidence a court will accept.",
    bio: [
      "Anjali is the firm's in-house financial forensic expert. Anjali's role is to turn disordered financial material into evidence a court will accept.",
      "She works for companies, organisations and individuals who have been the victims of crime, usually from the first meeting. Where a client arrives with a suspicion, a gap in the accounts or an unexplained payment run, she reconstructs ledgers, unwinds transfers, quantifies loss and identifies where the money went next.",
      "She builds the financial spine of private prosecutions: expert reports and schedules for the Crown Court, evidence at trial, and a narrative a jury can follow. Recovery sits in the same work — tracing through banks, nominees, property and wallets, and quantifying benefit for confiscation, civil claims and insurance.",
      "Anjali is unusually clear about what the numbers do and do not prove. Clients are told early when a case is stronger than they feared, and just as early when it is not.",
    ],
    experience: [
      "Reconstruction of three years of manipulated management accounts in a long-running invoicing fraud",
      "Tracing and quantification underpinning an emergency worldwide freezing order",
      "Expert evidence at trial in a private prosecution of a former finance director",
      "Benefit and available-amount analysis in confiscation following conviction",
    ],
  },
  {
    slug: "david-kerr",
    name: "David Kerr",
    shortName: "David Kerr",
    initials: "DK",
    role: "Lawyer — Fraud, Financial Crime & Private Prosecutions",
    firm: "Edison Law",
    featured: true,
    photo: "/images/people/david-kerr.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Lawyer in the financial crime team. Runs large, document-heavy matters from first instruction through to trial.",
    bio: [
      "David is a lawyer in the firm's financial crime team. David runs some of the firm's largest and most document-heavy matters from first instruction through to trial.",
      "He acts for companies, organisations and individuals who have been the victims of crime: boardroom and senior-management fraud, false accounting, misappropriation, procurement fraud, and losses through misrepresented investments. He is usually brought in once the problem is bigger than first thought, and his first task is to impose order on it.",
      "He conducts private prosecutions end to end — investigation, a criminal-standard file, disclosure, counsel and trial — on the basis that a sloppy case will not survive the defence. Recovery is settled at the outset: freezing, search and disclosure, restraint and confiscation, civil claims and insolvency where they reach the money faster.",
      "David is measured, decisive and good with clients under pressure. He supervises junior lawyers and insists every file can be picked up cold and understood.",
    ],
    experience: [
      "Private prosecutions of internal fraud, false accounting and misappropriation — investigation through to trial",
      "Emergency freezing, search and disclosure applications where value is still moving",
      "Parallel criminal, civil and insolvency strategy on the same facts",
      "Board-level internal investigations that may later have to be reported",
    ],
  },
  {
    slug: "amelia-rowe",
    name: "Amelia Rowe",
    shortName: "Amelia Rowe",
    initials: "AR",
    role: "Lawyer — Fraud, Financial Crime & Private Prosecutions",
    firm: "Edison Law",
    photo: "/images/people/amelia-rowe.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Lawyer in the financial crime team. Day-to-day conduct of cases from first instruction through to trial, and often the client's principal point of contact.",
    bio: [
      "Amelia is a lawyer in the firm's financial crime team. Amelia is closely involved in the day-to-day conduct of those cases, from first instruction through to trial.",
      "She acts for companies, organisations and individuals who have been the victims of crime: employee and fiduciary fraud, false accounting, misappropriation, supplier fraud and investment schemes affecting private individuals. She is often the client's principal point of contact in matters that are distressing as well as complex.",
      "She prepares case papers to a criminal evidential standard, drafts statements, manages disclosure, instructs counsel and attends court. Recovery work sits alongside: freezing, search and disclosure applications, tracing with forensic colleagues, and restraint, confiscation and civil claims at short notice.",
      "Amelia is precise, well organised and calm under pressure. Colleagues describe her as the person who has already found the document everyone else is still looking for.",
    ],
    experience: [
      "Case file and disclosure schedules in a private prosecution of a former employee for invoicing fraud",
      "Urgent freezing and search order following fiduciary misappropriation",
      "Acting for investors in a collapsed scheme, coordinating tracing and civil recovery",
      "Witness evidence and trial bundles in Crown Court proceedings",
    ],
  },
  {
    slug: "priya-sharma",
    name: "Priya Sharma",
    shortName: "Priya Sharma",
    initials: "PS",
    role: "Lawyer — Civil Recovery",
    firm: "Edison Law",
    photo: "/images/people/priya-sharma.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Lawyer in the financial crime team. Runs the civil claim that may reach the money when a prosecution is not the fastest route, or when it runs in parallel.",
    bio: [
      "Priya is a lawyer in the firm's financial crime team. Priya's practice is the civil side of that work: proprietary claims, deceit, knowing receipt and the injunctions that hold value while the claim proceeds.",
      "She acts for companies, organisations and individuals who have been the victims of crime. She is often instructed alongside a criminal file, so the civil claim and the prosecution are one strategy rather than two firms writing past each other.",
      "She prepares freezing and disclosure applications, pleadings that match the evidential file, and settlement positions that reflect what can actually be recovered. She takes the duties of candour on without-notice applications as seriously as the result.",
      "Priya is commercially minded and direct. She frames decisions in terms of outcome and cost, and will advise against a course the numbers do not support.",
    ],
    experience: [
      "Proprietary claims and freezing orders run in parallel with a private prosecution",
      "Knowing-receipt claims against companies that received diverted supplier payments",
      "Without-notice disclosure applications against banks holding converted proceeds",
      "Settlement advice once tracing shows where remaining value actually sits",
    ],
  },
  {
    slug: "liam-brennan",
    name: "Liam Brennan",
    shortName: "Liam Brennan",
    initials: "LB",
    role: "Financial Crime Investigator",
    firm: "Edison Law",
    featured: true,
    photo: "/images/people/liam-brennan.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Financial crime investigator in the firm's team. Establishes what happened, with a particular focus on cross-border enquiry.",
    bio: [
      "Liam is a financial crime investigator within the firm's team. Liam's role is to establish what happened — who was involved, how the scheme operated, and what evidence exists to prove it — before a strategy is chosen.",
      "He works for companies, organisations and individuals who have been the victims of crime, with a focus on cross-border investigation. He has spent much of his career on matters spanning Ireland, the UK and the wider EU: foreign registries, court records, insolvency files and procurement databases.",
      "He builds files that hold up: witnesses, statements, continuity and disclosure. Recovery work is the same method — nominee directors, connected companies, family members holding property, and people who have moved or gone to ground — so freezing, service and enforcement have facts underneath them.",
      "Liam is patient and quietly effective. He rarely reports anything until he can prove it, and he has a habit of producing the one document that changes the shape of a case.",
    ],
    experience: [
      "Procurement fraud spanning three European jurisdictions, identifying links between a manager and a supplier network",
      "Location of a defendant who had relocated abroad under a variant of his name",
      "Foreign registry and court records establishing control of companies used to receive diverted funds",
      "Witness enquiries and statements supporting a Crown Court private prosecution",
    ],
  },
  {
    slug: "sophie-lang",
    name: "Sophie Lang",
    shortName: "Sophie Lang",
    initials: "SL",
    role: "Payments Tracing Specialist",
    firm: "Edison Law",
    photo: "/images/people/sophie-lang.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Payments tracing specialist in the financial crime team. Follows diverted funds through banks, PSPs and e-money accounts in the first hours of a matter.",
    bio: [
      "Sophie is a payments tracing specialist in the firm's financial crime team. Sophie is brought in when the question is where a payment went — today, not next month.",
      "She acts for companies, organisations and individuals who have been the victims of crime, particularly payment diversion and authorised push payment fraud. Working from incomplete references, she maps movement through correspondent banks, payment institutions and e-money accounts, and produces the picture needed for an emergency application.",
      "That early tracing becomes evidence: flow-of-funds schedules, institution lists, and the disclosure routes against each. She will say when the trail has left the regulated system, and when it has not.",
      "Sophie is quick, composed under pressure, and good at explaining a funds trail to people hearing it for the first time. Clients often say she was the first person to make the situation feel manageable.",
    ],
    experience: [
      "Payments map completed within two days of a seven-figure diversion, supporting a proprietary injunction",
      "Identification of layered transfers through multiple payment institutions",
      "Exhibits prepared for a private prosecution of a former employee who altered payee details",
      "Loss schedule for parallel civil proceedings and an insurance notification",
    ],
  },
  {
    slug: "oliver-bennett",
    name: "Oliver Bennett",
    shortName: "Oliver Bennett",
    initials: "OB",
    role: "Lawyer — Fraud, Financial Crime & Private Prosecutions",
    firm: "Edison Law",
    photo: "/images/people/oliver-bennett.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Lawyer in the financial crime team. Often the first person a client speaks to once a fraud surfaces: get hold of the matter, say what can be achieved, push it forward.",
    bio: [
      "Oliver is a lawyer in the firm's financial crime team. Oliver's practice sits at the operational heart of it: getting hold of a new matter fast, working out what can actually be achieved, and pushing it forward.",
      "He acts for companies, organisations and individuals who have been the victims of crime — director and employee fraud, false accounting, misappropriation, supplier fraud, and losses through dishonest investment arrangements. He is frequently the first person a client speaks to, and he gives a straight assessment, including when the answer is unwelcome.",
      "He prepares cases to a criminal evidential standard, manages disclosure, works with investigators and forensic experts, and attends throughout proceedings. Recovery runs through the same file: urgent freezing, search and disclosure, restraint and confiscation, and civil or insolvency claims where they reach the money faster.",
      "Oliver is direct, tenacious and steady with clients who are anything but. Colleagues say he gets a chaotic new file into order quicker than anyone expects.",
    ],
    experience: [
      "Private prosecution of a former director for misappropriation of company funds",
      "Freezing and disclosure applications issued within days of a fraud being discovered",
      "Parallel criminal and civil claims arising from supplier fraud",
      "Internal investigation into senior employee expenses and false invoicing",
    ],
  },
  {
    slug: "andrew-haddon",
    name: "Andrew Haddon",
    shortName: "Andrew Haddon",
    initials: "AH",
    role: "Asset Tracing Specialist",
    firm: "Edison Law",
    featured: true,
    photo: "/images/people/andrew-haddon.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Asset tracing specialist in the financial crime team. Locates recoverable value and says, early, whether pursuing it is worth the cost.",
    bio: [
      "Andrew is an asset tracing specialist within the firm's financial crime team. Andrew's role addresses the question every victim of fraud eventually asks: where has the money gone, and is any of it still there.",
      "He works for companies, organisations and individuals who have been the victims of crime. He follows funds from the point of loss through banks, payment institutions and corporate accounts, and identifies where proceeds have been converted — property, vehicles, investments, goods or digital assets — and in whose name they are held. Where a defendant appears to be worth nothing, he tests whether that is true.",
      "He produces tracing evidence that stands up in court: flow-of-funds schedules, asset registers and exhibits for restraint, confiscation and freezing. He assesses not only whether an asset can be found but whether pursuing it is economically worthwhile, including before litigation begins.",
      "Andrew is methodical, discreet and realistic. Clients are told early when there is value to pursue — and equally early when the trail ends.",
    ],
    experience: [
      "Tracing exercise across five jurisdictions establishing the destination of misappropriated group funds",
      "Identification of residential property held through a nominee, supporting a proprietary freezing order",
      "Asset register prepared for restraint and confiscation following conviction",
      "Pre-action enforceability assessment that redirected strategy toward a solvent third party",
    ],
  },
  {
    slug: "rosalind-keane",
    name: "Rosalind Keane",
    shortName: "Rosalind Keane",
    initials: "RK",
    role: "Confiscation Specialist",
    firm: "Edison Law",
    photo: "/images/people/rosalind-keane.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Confiscation specialist in the financial crime team. Turns a conviction or a settlement into a recoverable amount: benefit, available assets, and the orders that actually reach them.",
    bio: [
      "Rosalind is a confiscation specialist in the firm's financial crime team. Rosalind's job is the part that comes after the verdict: making sure the benefit figure, the available amount and the enforcement route are ready before anyone assumes the money will come back.",
      "She acts for companies, organisations and individuals who have been the victims of crime. She prepares confiscation and compensation files, tests what a defendant actually owns, and works with tracing and forensic colleagues so hidden value is on the schedule rather than discovered too late.",
      "Rosalind supports advice on the best means of retrieving assets linked to the offending by coordinating restraint, confiscation and civil enforcement as one sequence, not three afterthoughts. She is precise about what POCA will reach and what it will not.",
      "She is calm, exact and unwilling to inflate a figure that will not survive a hearing. Clients are told the recoverable position, not the hopeful one.",
    ],
    experience: [
      "Benefit and available-amount analysis following conviction in a private prosecution of a finance director",
      "Restraint varied after hidden property and nominee holdings were identified",
      "Compensation schedule prepared alongside confiscation so the victim's claim was not left to the end",
      "Enforcement against assets transferred to family members ahead of sentencing",
    ],
  },
  {
    slug: "julian-vance",
    name: "Julian Vance",
    shortName: "Julian Vance",
    initials: "JV",
    role: "Forensic Accountant",
    firm: "Edison Law",
    featured: true,
    photo: "/images/people/julian-vance.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Forensic accountant in the financial crime team. Rebuilds the books, states what the numbers prove, and writes reports that can be cross-examined.",
    bio: [
      "Julian is a forensic accountant in the firm's financial crime team. Julian's role is to turn disordered accounts into a financial narrative a court can follow.",
      "He acts for companies, organisations and individuals who have been the victims of crime. He reconstructs ledgers, unwinds intercompany transfers, quantifies loss and identifies the point at which money left the client's control. He will say, early, when the records do not support the allegation.",
      "His reports and schedules are written for trial, confiscation and civil recovery. He works with counsel on the figures that will actually be tested, and with investigators on the documents those figures need.",
      "Julian is measured and difficult to rush. Colleagues bring him the file when the story is bigger than the evidence.",
    ],
    experience: [
      "Reconstruction of manipulated management accounts establishing the mechanism of a long-running invoicing fraud",
      "Loss quantification supporting an emergency proprietary injunction",
      "Expert report and schedules prepared for a Crown Court private prosecution",
      "Transaction testing after internal fraud in a payments business",
    ],
  },
  {
    slug: "samira-rahman",
    name: "Samira Rahman",
    shortName: "Samira Rahman",
    initials: "SR",
    role: "Corporate Intelligence Analyst",
    firm: "Edison Law",
    photo: "/images/people/samira-rahman.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Corporate intelligence analyst in the financial crime team. Establishes who a counterparty is, what they own, and whether a claim against them is worth the cost — before money is spent.",
    bio: [
      "Samira is a corporate intelligence analyst in the firm's financial crime team. Samira's work sits before the first letter: who the other side actually is, and whether they can satisfy a judgment.",
      "She acts for companies, organisations and individuals who have been the victims of crime, and for boards instructing enhanced due diligence before a transaction, appointment or investment. She maps undisclosed litigation, connected companies, political exposure and assets held through nominees.",
      "Her findings inform recovery strategy as much as they inform whether to proceed at all. Samira is careful about method: open-source and registry work first, visible steps only on instruction.",
      "She is discreet, thorough and unwilling to overstate a connection she cannot prove. Clients value a short answer when the trail is thin.",
    ],
    experience: [
      "Pre-action intelligence on a counterparty showing the judgment would not be worth enforcing",
      "Mapping of connected companies and family holdings used to receive diverted funds",
      "Source-of-wealth review before a high-value appointment",
      "Integrity report supporting an internal investigation into a joint-venture partner",
    ],
  },
  {
    slug: "imogen-vale",
    name: "Imogen Vale",
    shortName: "Imogen Vale",
    initials: "IV",
    role: "Digital Forensics Analyst",
    firm: "Edison Law",
    photo: "/images/people/imogen-vale.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Digital forensics analyst in the financial crime team. Preserves devices, mailboxes and logs so the digital record still exists when the legal route is chosen.",
    bio: [
      "Imogen is a digital forensics analyst in the firm's financial crime team. Imogen's first task is preservation: hold the device, the mailbox and the log before anyone tidies the file.",
      "She acts for companies, organisations and individuals who have been the victims of crime. She images machines, captures accounts, records access, and produces exhibits with continuity intact. She will stop a well-meaning export that would destroy metadata.",
      "Her work feeds both investigation and recovery: payment records, deleted mail, device histories that show who moved what, and when. She writes method so it can be explained later, including under cross-examination.",
      "Imogen is exact, quiet and difficult to fluster. The team calls her before anyone logs in.",
    ],
    experience: [
      "Imaging of laptops and phones in the first day of an internal fraud, before accounts were reset",
      "Mailbox preservation supporting a private prosecution of a former employee",
      "Continuity records for digital evidence used on an urgent search order",
      "Recovery of deleted payment instructions showing a supplier diversion",
    ],
  },
  {
    slug: "caroline-reid",
    name: "Caroline Reid",
    shortName: "Caroline Reid",
    initials: "CR",
    role: "Lawyer — Restraint & Freezing",
    firm: "Edison Law",
    photo: "/images/people/caroline-reid.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Lawyer in the financial crime team, focused on restraint and freezing. Prepares the application that stops the money moving, then keeps the order in place.",
    bio: [
      "Caroline is a lawyer in the firm's financial crime team, with a practice in restraint and freezing. Caroline is instructed when value is still moving and a delay will cost the client the asset.",
      "She acts for companies, organisations and individuals who have been the victims of crime. She prepares worldwide and proprietary freezing applications, Bankers Trust and Norwich Pharmacal orders, and the evidence packs those applications require — often on very short notice.",
      "Asset recovery is the point of the work, not a sequel. Caroline coordinates with tracing and forensic colleagues so the order names the right institutions, and she manages the undertakings and variations that follow.",
      "She is organised, direct with clients under pressure, and careful not to ask a court for more than the evidence will carry.",
    ],
    experience: [
      "Worldwide and proprietary freezing applications where a fiduciary's misappropriation has just come to light",
      "Proprietary injunctions supported by a payments-tracing picture assembled in days",
      "Disclosure orders against banks holding diverted balances",
      "Variation and enforcement of freezing orders after assets are moved into a nominee's name",
    ],
  },
  {
    slug: "evelyn-boateng",
    name: "Evelyn Boateng",
    shortName: "Evelyn Boateng",
    initials: "EB",
    role: "Financial Crime Investigator",
    firm: "Edison Law",
    featured: true,
    photo: "/images/people/evelyn-boateng.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Financial crime investigator in the firm's team. Finds the people, the witnesses and the documents that turn a suspicion into a file.",
    bio: [
      "Evelyn is a financial crime investigator within the firm's team. Evelyn's role is to establish who did what — and to put that in a form that will hold up.",
      "She acts for companies, organisations and individuals who have been the victims of crime. She identifies witnesses, takes statements, gathers documents and maintains continuity. She locates people who have moved, changed name, or gone to ground, including for service.",
      "Much of her work is directed at recovery: the connected supplier, the family member holding property, the person who can be found. Findings are logged so they can be disclosed without embarrassment.",
      "Evelyn is patient and persistent. She reports when she can prove it, not when the story is interesting.",
    ],
    experience: [
      "Witness statements and unused-material records supporting a Crown Court private prosecution",
      "Location of a defendant who had left the jurisdiction under a variant of her name",
      "Enquiries establishing undisclosed links between an internal manager and a supplier",
      "Employee interviews following a whistleblower report of falsified invoicing",
    ],
  },
  {
    slug: "marcus-quinn",
    name: "Marcus Quinn",
    shortName: "Marcus Quinn",
    initials: "MQ",
    role: "Crypto Tracing Analyst",
    firm: "Edison Law",
    featured: true,
    photo: "/images/people/marcus-quinn.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Crypto tracing analyst in the financial crime team. Maps wallets, exchanges and cash-outs, and states what on-chain data can and cannot prove.",
    bio: [
      "Marcus is a crypto tracing analyst in the firm's financial crime team. Marcus maps where digital value went — through wallets, mixers, bridges and exchanges — without pretending the chain shows more than it does.",
      "He acts for companies, organisations and individuals who have been the victims of crime, including wallet theft, investment scams and conversion of diverted fiat into digital assets. He produces clustering, hop maps and exchange-attribution that can be exhibited, and he flags when a hop is inference rather than fact.",
      "His work supports emergency applications against exchanges and the later trial file. He liaises on freeze requests and writes the limits of the tracing into the report, so counsel is not surprised in court.",
      "Marcus is precise and unimpressed by theatre. He will say when the coins have cashed out, and when they have not.",
    ],
    experience: [
      "Wallet mapping supporting an emergency freeze request to a regulated exchange",
      "Tracing of proceeds converted from a payment diversion into digital assets and back into banking",
      "Exhibits for a private prosecution involving an unregulated trading platform",
      "Attribution report distinguishing confirmed exchange deposits from inferred clustering",
    ],
  },
  {
    slug: "robert-hale",
    name: "Robert Hale",
    shortName: "Robert Hale",
    initials: "RH",
    role: "Senior Asset Recovery Specialist",
    firm: "Edison Law",
    featured: true,
    photo: "/images/people/robert-hale.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Senior asset recovery specialist in the financial crime team. Decides which assets are worth reaching, in which order, and by which remedy.",
    bio: [
      "Robert is a senior asset recovery specialist in the firm's financial crime team. Robert holds the recovery strategy: which asset, which court, which order, and at what cost.",
      "He acts for companies, organisations and individuals who have been the victims of crime. He works from tracing and intelligence already in hand, then sequences freezing, disclosure, receivership and enforcement so effort is not spent on value that cannot be reached.",
      "He coordinates local counsel overseas, insolvency routes where they are faster, and the difference between an asset that exists and an asset that can be sold. He will advise against a chase that will cost more than it returns.",
      "Robert is commercial and unsentimental. Clients get a plan, and they get told when the plan should stop.",
    ],
    experience: [
      "Recovery strategy combining a proprietary freeze, disclosure against banks and later receivership",
      "Enforcement against property held through a nominee after tracing identified the true controller",
      "Insolvency route used to reach assets faster than a free-standing claim",
      "Decision to abandon overseas enforcement where the cost exceeded likely recovery",
    ],
  },
];
