export function personEmail(person) {
  if (person?.email) return person.email;
  const local = String(person?.slug || "").replaceAll("-", ".");
  return local ? `${local}@edisonlaw.co.uk` : "";
}

export function personPhone(person) {
  return String(person?.phone || "").trim();
}

export function personTelegramHref(person) {
  const phone = personPhone(person);
  if (!phone) return "";
  return `https://t.me/${phone.replace(/[^\d+]/g, "")}`;
}

export const people = [
  {
    slug: "richard-edison",
    name: "Richard Edison",
    shortName: "Richard Edison",
    initials: "RE",
    role: "Owner",
    firm: "Edison Law",
    principal: true,
    featured: true,
    photo: "/images/people/richard-edison.png",
    photoWidth: 570,
    photoHeight: 380,
    practicePhoto: "/images/people/richard-edison-practice.png",
    practicePhotoWidth: 626,
    practicePhotoHeight: 417,
    summary:
      "Owner of Edison Law, an SRA-regulated sole practice in London.",
    bio: [
      "Richard Edison is named on this site as the owner of Edison Law. The firm is an SRA-regulated sole practice in London advising on criminal, investigative and recovery matters involving fraud and financial misconduct.",
      "Each instruction is supervised by a named solicitor. Specialist investigators and forensic professionals are introduced where their expertise is needed, with their role and status explained.",
      "Confirm current authorised individuals on the public SRA record. Job titles on this site are not a reserved-activity authorisation.",
    ],
  },
  {
    slug: "david-kerr",
    name: "David Kerr",
    shortName: "David Kerr",
    initials: "DK",
    role: "Financial Crime & Private Prosecutions Solicitor",
    firm: "Edison Law",
    featured: true,
    photo: "/images/people/david-kerr.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Assesses evidence and advises on financial-crime strategy and private prosecutions.",
    bio: [
      "David is a solicitor specialising in financial-crime matters and private prosecutions. He assesses the available evidence, identifies the legal questions that must be resolved and advises whether criminal proceedings are realistic and proportionate.",
      "His work includes document-heavy fraud allegations, witness evidence, disclosure, instructions to counsel and coordination with investigators and forensic specialists. Where appropriate, he considers recovery options alongside the prosecution strategy so that each route supports the wider objectives of the matter.",
      "David gives clients a clear account of the available legal routes, evidential weaknesses, likely costs and procedural risks before substantial steps are taken.",
    ],
    areas: [
      "Private-prosecution assessment and case preparation",
      "Fraud and financial-crime evidence",
      "Disclosure and counsel coordination",
      "Parallel prosecution and recovery strategy",
    ],
  },
  {
    slug: "amelia-rowe",
    name: "Amelia Rowe",
    shortName: "Amelia Rowe",
    initials: "AR",
    role: "Fraud & Investigations Solicitor",
    firm: "Edison Law",
    photo: "/images/people/amelia-rowe.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Coordinates legal, evidential and recovery work in fraud investigations.",
    bio: [
      "Amelia is a solicitor working on fraud and investigation matters. She reviews the available records at an early stage, identifies material that must be preserved and defines the factual questions that should be investigated first.",
      "Her work includes witness preparation, chronologies, document review, disclosure and coordination with tracing and forensic specialists. She keeps the legal strategy tied to evidence that can be tested rather than assumptions formed at the start of a matter.",
      "Amelia explains the purpose of each investigative step and turns the resulting material into a structured file capable of supporting advice, proceedings or a decision not to proceed.",
    ],
    areas: [
      "Fraud and internal investigations",
      "Evidence preservation and case chronology",
      "Witness and document preparation",
      "Coordination of legal and specialist work",
    ],
  },
  {
    slug: "liam-brennan",
    name: "Liam Brennan",
    shortName: "Liam Brennan",
    initials: "LB",
    role: "Financial Crime Investigator",
    firm: "Edison Law",
    featured: true,
    photo: "/images/people/liam-brennan.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Builds testable records of participants and events in financial-crime matters.",
    bio: [
      "Liam's role is to establish what happened before a legal route is selected. He works from records, witnesses and lawful enquiries to identify participants, relationships, events and gaps in the available evidence.",
      "The resulting material is organised so that sources can be checked and findings can be distinguished from inference. Where facts or records sit overseas, enquiries are coordinated with appropriately qualified local professionals when required.",
      "Investigative findings are assessed by the solicitor responsible for the matter. Liam's role does not include providing reserved legal services.",
    ],
    areas: [
      "Financial-crime fact development",
      "Witness and records enquiries",
      "Corporate, court and insolvency records",
      "Cross-border investigation support",
    ],
  },
  {
    slug: "sophie-lang",
    name: "Sophie Lang",
    shortName: "Sophie Lang",
    initials: "SL",
    role: "Payments & Transaction Tracing Specialist",
    firm: "Edison Law",
    photo: "/images/people/sophie-lang.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Maps payment flows to support preservation, disclosure and recovery decisions.",
    bio: [
      "Sophie's role focuses on the movement of fiat payments after fraud, diversion or unauthorised activity. She works from transaction records, payment references and institution information to build a clear flow-of-funds picture.",
      "The output may include transaction schedules, institution lists, timelines and identified gaps in the record. It is prepared to support decisions about bank contact, evidence preservation, disclosure routes and possible urgent relief.",
      "A payment trail does not itself establish liability or guarantee recovery. Legal conclusions and applications are handled through the regulated legal team.",
    ],
    areas: [
      "Bank and payment-institution tracing",
      "Authorised push payment and payment diversion records",
      "Flow-of-funds schedules",
      "Transaction evidence for recovery decisions",
    ],
  },
  {
    slug: "oliver-bennett",
    name: "Oliver Bennett",
    shortName: "Oliver Bennett",
    initials: "OB",
    role: "Fraud & Asset Recovery Solicitor",
    firm: "Edison Law",
    photo: "/images/people/oliver-bennett.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Advises on fraud, asset preservation and proportionate recovery options.",
    bio: [
      "Oliver is a solicitor advising on fraud and asset-recovery matters. He identifies the relevant parties, assesses the evidence already available and considers which assets may remain reachable before a client commits to substantial expenditure.",
      "His work may combine investigator findings, transaction tracing and disclosure applications with advice on civil, criminal and insolvency routes. Each option is assessed against the evidence, urgency, likely cost and practical prospects of enforcement.",
      "Oliver does not treat identification of an asset as proof that it can be recovered. Clients receive a clear scope, an explanation of the available routes and a proportionate sequence for the next steps.",
    ],
    areas: [
      "Early fraud and recovery assessment",
      "Evidence and asset preservation",
      "Freezing and disclosure strategy",
      "Coordination of civil, criminal and insolvency routes",
    ],
  },
  {
    slug: "andrew-haddon",
    name: "Andrew Haddon",
    shortName: "Andrew Haddon",
    initials: "AH",
    role: "Asset Tracing & Recovery Specialist",
    firm: "Edison Law",
    featured: true,
    photo: "/images/people/andrew-haddon.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Maps assets and ownership to assess reachability, routes and cost.",
    bio: [
      "Andrew's role is to identify potentially recoverable value and the people or entities that appear to own or control it. Enquiries may follow funds into companies, property, investments, goods or digital assets.",
      "Findings are organised as asset registers, ownership maps and source-referenced schedules. The work separates the existence of an asset from the separate legal questions of ownership, jurisdiction and enforceability.",
      "Tracing is used to inform a decision, not to promise a result. Any freezing, disclosure or enforcement step is advised on and supervised by the legal team.",
    ],
    areas: [
      "Asset and ownership mapping",
      "Connected companies and nominee structures",
      "Property, investment and digital-asset enquiries",
      "Pre-action enforceability assessment",
    ],
  },
  {
    slug: "rosalind-keane",
    name: "Rosalind Keane",
    shortName: "Rosalind Keane",
    initials: "RK",
    role: "Confiscation & Proceeds of Crime Specialist",
    firm: "Edison Law",
    photo: "/images/people/rosalind-keane.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Organises benefit, asset and available-amount evidence for proceeds-of-crime matters.",
    bio: [
      "Rosalind's role focuses on the financial record needed for confiscation and related proceeds-of-crime decisions. She works with accounting and tracing material to distinguish alleged benefit, identified assets and the amounts that may in fact be available.",
      "The work may include financial schedules, compensation material, asset information and coordination with those handling restraint or enforcement. Figures are tied back to source records and stated with their limitations.",
      "Confiscation and restraint are legal processes with statutory tests. Advice, advocacy and reserved work are provided through appropriately authorised lawyers.",
    ],
    areas: [
      "Benefit and available-amount schedules",
      "Confiscation and compensation material",
      "Restraint-related asset information",
      "Coordination with forensic and tracing work",
    ],
  },
  {
    slug: "julian-vance",
    name: "Julian Vance",
    shortName: "Julian Vance",
    initials: "JV",
    role: "Forensic Accountant",
    firm: "Edison Law",
    featured: true,
    photo: "/images/people/julian-vance.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Reconstructs records and tests loss calculations for legal proceedings.",
    bio: [
      "Julian's role is to turn accounting records into a clear, source-referenced financial analysis. That can involve reconstructing ledgers, reviewing intercompany movements, testing transactions and distinguishing recorded loss from unsupported assumption.",
      "His schedules are prepared for use by the legal and investigative team in advice, pleadings, witness evidence, confiscation analysis or cross-examination. Where the records do not support a proposed conclusion, the limitation is stated.",
      "The scope of any expert evidence and the capacity in which it is given are confirmed for the particular instruction. The profile does not make a general claim of expert appointment.",
    ],
    areas: [
      "Ledger and transaction reconstruction",
      "Loss and benefit calculations",
      "Intercompany and related-party analysis",
      "Financial schedules for proceedings",
    ],
  },
  {
    slug: "imogen-vale",
    name: "Imogen Vale",
    shortName: "Imogen Vale",
    initials: "IV",
    role: "Digital Forensics & Evidence Analyst",
    firm: "Edison Law",
    photo: "/images/people/imogen-vale.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Preserves digital evidence with provenance, continuity and limitations recorded.",
    bio: [
      "Imogen's role begins with preservation. Devices, mailboxes, cloud accounts and logs may need to be held before ordinary use, exports or account changes alter the available record.",
      "The work records how material was collected, what metadata remains and which limitations affect interpretation. Outputs may include preservation notes, device or account captures, timelines and exhibits for review by lawyers and investigators.",
      "Digital collection is scoped according to authority, relevance, privacy and privilege. Legal decisions about use and disclosure remain with the solicitor responsible for the matter.",
    ],
    areas: [
      "Device and account preservation",
      "Mailbox, log and metadata review",
      "Continuity and collection records",
      "Digital timelines and exhibits",
    ],
  },
  {
    slug: "abigail-wills",
    name: "Abigail Charlotte Wills",
    shortName: "Abigail Charlotte Wills",
    initials: "ACW",
    role: "SRA-regulated solicitor",
    firm: "Edison Law",
    sraRegulated: true,
    email: "abi.wills@edisonlaw.co.uk",
    photo: "/images/people/abigail-wills.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "SRA-regulated solicitor named on the public organisation record for Edison Law.",
    bio: [
      "Abigail Charlotte Wills is an SRA-regulated solicitor. She is the solicitor named on the public SRA organisation record for Edison Law, a recognised sole practice authorised and regulated under SRA number 510498.",
      "Reserved legal work at the practice is carried out by a solicitor. Confirm her current practising status on the public SRA register. Job titles on this site are not a substitute for that record.",
      "The organisation record currently lists criminal work among the firm's areas of law. Instructions are accepted in writing after conflict checks.",
    ],
    areas: [
      "SRA-authorised reserved legal work",
      "Recognised sole practice",
      "Criminal work listed on the SRA record",
      "Public SRA organisation record",
    ],
  },
  {
    slug: "marcus-quinn",
    name: "Marcus Quinn",
    shortName: "Marcus Quinn",
    initials: "MQ",
    role: "Crypto & Digital Asset Tracing Analyst",
    firm: "Edison Law",
    featured: true,
    photo: "/images/people/marcus-quinn.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Maps digital assets, separating confirmed transactions from analytical inference.",
    bio: [
      "Marcus's role focuses on what public blockchain records can establish about the movement of digital assets. Transactions may be mapped across wallets, bridges, swaps and identifiable services, including possible exchange deposit points.",
      "The analysis records transaction identifiers, timestamps and methodology. Confirmed transfers are separated from clustering, attribution and other inferences so the legal team can assess what additional platform, device or identity evidence is required.",
      "On-chain tracing cannot reverse a transaction or prove control of a wallet by itself. Requests to platforms and any court application are handled through the appropriate legal route.",
    ],
    areas: [
      "Wallet and transaction mapping",
      "Bridges, swaps and exchange deposit points",
      "Service attribution and clustering limits",
      "Trace reports and supporting exhibits",
    ],
  },
  {
    slug: "robert-hale",
    name: "Robert Hale",
    shortName: "Robert Hale",
    initials: "RH",
    role: "Senior Asset Recovery Specialist",
    firm: "Edison Law",
    featured: true,
    phone: "+44 77 0681 8965",
    photo: "/images/people/robert-hale.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Coordinates asset reachability, recovery routes and cost-benefit decisions.",
    bio: [
      "Robert's role is to bring tracing, legal remedies and enforcement economics into one recovery plan. Identified assets are assessed by location, apparent ownership, security, liquidity and the process that may be required to reach them.",
      "The plan may involve disclosure, freezing, insolvency, receivership or enforcement steps, with local counsel engaged where foreign law or procedure is required. Each stage is reviewed against likely value, delay and cost.",
      "An asset that can be identified is not necessarily an asset that can be recovered. Legal advice and reserved work remain with the solicitor responsible for the matter.",
    ],
    areas: [
      "Recovery planning and sequencing",
      "Enforcement and insolvency options",
      "Cross-border recovery coordination",
      "Cost and recoverability review",
    ],
  },
  {
    slug: "clara-whitfield",
    name: "Clara Whitfield",
    shortName: "Clara Whitfield",
    initials: "CW",
    role: "Disclosure & Unused Material Solicitor",
    firm: "Edison Law",
    photo: "/images/people/clara-whitfield.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Advises on disclosure and continuing review in financial-crime proceedings.",
    bio: [
      "Clara is a solicitor focusing on disclosure and unused material in private prosecutions and financial-crime matters. She treats disclosure as a continuing legal duty rather than an administrative exercise left until the end of a case.",
      "Her work includes disclosure strategy, unused-material schedules, continuity records and liaison with those collecting digital, financial and witness evidence. Material is reviewed against issues it may support or undermine as the case and defence position develop.",
      "Clara advises on the prosecutor's duties of disclosure and fairness, ensuring that charging and disclosure decisions are documented and kept under review throughout proceedings.",
    ],
    areas: [
      "Disclosure strategy and review",
      "Unused-material schedules",
      "Continuity and exhibit records",
      "Ongoing review in private prosecutions",
    ],
  },
  {
    slug: "thomas-ellery",
    name: "Thomas Ellery",
    shortName: "Thomas Ellery",
    initials: "TE",
    role: "Private Prosecutions & Financial Crime Solicitor",
    firm: "Edison Law",
    phone: "+44 73 9551 0006",
    photo: "/images/people/thomas-ellery.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Assesses evidence and advises whether private prosecution is justified.",
    bio: [
      "Thomas is a solicitor advising on private prosecutions and financial-crime matters. He assesses the alleged conduct, available evidence and legal test for commencing criminal proceedings before recommending a prosecution route.",
      "He coordinates preservation, witness material, unused material and the early case file with investigators, forensic specialists and counsel where required. Related civil or recovery steps are identified so that one route does not unintentionally compromise another.",
      "Thomas advises clients on merits, prosecutorial duties, cost and procedural risk before proceedings are commenced. A private prosecution is not guaranteed to begin or succeed, and the CPS retains the power to take it over.",
    ],
    areas: [
      "Private-prosecution merits assessment",
      "Early evidence and witness preparation",
      "Disclosure and prosecutorial duties",
      "Coordination with recovery and civil routes",
    ],
  },
  {
    slug: "hannah-croft",
    name: "Hannah Croft",
    shortName: "Hannah Croft",
    initials: "HC",
    role: "Internal Investigations Specialist",
    firm: "Edison Law",
    photo: "/images/people/hannah-croft.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Structures internal investigations, evidence preservation and factual findings.",
    bio: [
      "Hannah's role focuses on the structure and factual record of internal enquiries. The work begins by defining the questions, decision-makers, material to be preserved and relationship with any employment, regulatory or criminal process.",
      "She may coordinate document holds, interviews, timelines and reporting with lawyers and digital specialists. Findings identify what is established, what remains disputed and what material supports each conclusion.",
      "Privilege, reporting obligations and legal consequences are assessed by the solicitor responsible for the matter. An internal investigation is not treated as a predetermined route to dismissal or prosecution.",
    ],
    areas: [
      "Whistleblower and internal-fraud enquiries",
      "Document holds and interview planning",
      "Investigation chronologies and findings",
      "Coordination with employment and regulatory work",
    ],
  },
  {
    slug: "hugh-penton",
    name: "Hugh Penton",
    shortName: "Hugh Penton",
    initials: "HP",
    role: "Solicitor — Regulatory Defence & Investigations",
    firm: "Edison Law",
    photo: "/images/people/hugh-penton.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Advises on early regulatory responses, privilege, notices and interviews.",
    bio: [
      "Hugh is a solicitor advising individuals and organisations when a regulator or enforcement authority has made contact or an investigation is expected. His initial advice addresses evidence preservation, privilege, communications and the scope of any compulsory power.",
      "His work includes information notices, interviews under caution, internal fact development and coordination with related civil or recovery issues. Advice is based on the named authority, the power being used and the documents actually available.",
      "Hugh helps clients understand their immediate obligations, available protections and the decisions that should be recorded. Regulatory processes differ materially, so the response is tailored to the particular regime and stage of the matter.",
    ],
    areas: [
      "Urgent investigation response",
      "Privilege and evidence preservation",
      "Information notices and interviews",
      "Parallel regulatory, civil and recovery issues",
    ],
  },
  {
    slug: "edward-langford",
    name: "Edward Langford",
    shortName: "Edward Langford",
    initials: "EL",
    role: "Solicitor — Cross-Border Fraud & Corruption",
    firm: "Edison Law",
    photo: "/images/people/edward-langford.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Coordinates cross-border fraud and recovery matters with local counsel.",
    bio: [
      "Edward is a solicitor advising on fraud and corruption matters where important facts, people or assets sit in more than one jurisdiction. He assesses forum, service, evidence, interim relief and enforceability before proceedings are issued.",
      "He coordinates appropriately qualified local counsel for foreign-law advice and procedural steps, with the client's approval. Registry, tracing and investigative work is integrated into a single legal timetable.",
      "Edward gives clients a practical view of recognition, enforcement, delay and cost in each relevant jurisdiction. An English order does not automatically operate overseas, and the cross-border plan reflects that limitation.",
    ],
    areas: [
      "Forum, defendant and asset mapping",
      "Service and evidence across borders",
      "Local-counsel coordination",
      "Recognition and enforcement planning",
    ],
  },
  {
    slug: "daniel-crowe",
    name: "Daniel Crowe",
    shortName: "Daniel Crowe",
    initials: "DC",
    role: "Financial Crime Investigator",
    firm: "Edison Law",
    phone: "+44 74 0116 7747",
    photo: "/images/people/daniel-crowe.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Links documents, transactions, witnesses and participants into a testable record.",
    bio: [
      "Daniel's role is to test an allegation against the records that still exist. He identifies relevant people, source documents, transaction information and missing material, then organises findings around the agreed investigative questions.",
      "The work may include witness enquiries, chronologies, continuity records and links between recipients, companies or accounts. Findings and unresolved inferences are kept separate.",
      "The investigation informs legal advice; it does not determine guilt or select a legal route on its own. Those decisions remain with the supervising solicitor.",
    ],
    areas: [
      "Fraud and financial-crime enquiries",
      "Witness and source-document development",
      "Chronologies and continuity records",
      "Participant and transaction mapping",
    ],
  },
  {
    slug: "simon-blake",
    name: "Simon Blake",
    shortName: "Simon Blake",
    initials: "SB",
    role: "Solicitor — Crypto Fraud & Digital Assets",
    firm: "Edison Law",
    photo: "/images/people/simon-blake.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Advises on crypto tracing, preservation, disclosure and interim relief.",
    bio: [
      "Simon is a solicitor advising on crypto fraud and digital-asset disputes. He assesses on-chain transfers alongside platform correspondence, device evidence and identity material because a wallet trail alone rarely proves ownership or control.",
      "He works with tracing analysts on preservation requests, platform engagement, proprietary claims, interim relief and the choice between civil and criminal routes. Confirmed transactions are kept distinct from technical inference and attribution.",
      "Simon explains what the available evidence can support, which legal route may be proportionate and where further disclosure is needed. Digital-asset recovery remains fact-sensitive and cannot be guaranteed.",
    ],
    areas: [
      "Crypto-fraud legal assessment",
      "Platform preservation and disclosure routes",
      "Proprietary and interim-relief analysis",
      "Civil and criminal route selection",
    ],
  },
  {
    slug: "helen-ashworth",
    name: "Helen Ashworth",
    shortName: "Helen Ashworth",
    initials: "HA",
    role: "Solicitor — Tax Investigations & HMRC",
    firm: "Edison Law",
    photo: "/images/people/helen-ashworth.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Advises on HMRC enquiries, notices, privilege and document scope.",
    bio: [
      "Helen is a solicitor advising on HMRC enquiries and tax-related investigations. She identifies what a request requires, which records answer it and which legal or evidential issues arise from the proposed response.",
      "Her work includes document scoping, privilege review, chronology and coordination with specialist tax advisers where substantive tax advice is required. Civil enquiries, information notices and criminal investigations are treated as distinct processes.",
      "Helen helps clients provide an accurate, proportionate response while keeping related fraud, recovery and reporting issues visible. Her role does not include tax-return preparation, and the outcome or duration of an enquiry cannot be predicted.",
    ],
    areas: [
      "HMRC enquiries and information notices",
      "Document scope and privilege review",
      "Investigation chronology and evidence",
      "Coordination with specialist tax advice",
    ],
  },
  {
    slug: "graham-holt",
    name: "Graham Holt",
    shortName: "Graham Holt",
    initials: "GH",
    role: "Pre-Litigation Intelligence Specialist",
    firm: "Edison Law",
    photo: "/images/people/graham-holt.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Develops lawful pre-litigation intelligence on counterparties, connections and assets.",
    bio: [
      "Graham's role sits before litigation, investment or another material decision. Public records, corporate filings, litigation information and lawful open-source research are used to clarify identity, control, connections and apparent enforceability.",
      "Findings are source-referenced and qualified. A corporate connection, shared address or online association is not treated as proof of ownership or misconduct.",
      "The purpose and visibility of each enquiry are agreed in advance. Legal advice on whether to proceed is given through the regulated legal team.",
    ],
    areas: [
      "Counterparty and corporate-record research",
      "Connected-entity mapping",
      "Apparent asset and enforceability review",
      "Pre-litigation and decision-support reporting",
    ],
  },
];
