export const people = [
  {
    slug: "richard-edison",
    name: "Richard Edison",
    shortName: "Richard Edison",
    initials: "RE",
    role: "Owner",
    firm: "Edison Law",
    principal: true,
    featured: true,
    photo: "/images/people/richard-edison.png",
    photoWidth: 570,
    photoHeight: 380,
    practicePhoto: "/images/people/richard-edison-practice.png",
    practicePhotoWidth: 626,
    practicePhotoHeight: 417,
    summary:
      "Owner of Edison Law, an SRA-regulated sole practice in London.",
    bio: [
      "Richard Edison is named on this site as the owner of Edison Law. The firm is an SRA-regulated sole practice in London advising on criminal, investigative and recovery matters involving fraud and financial misconduct.",
      "Each instruction is supervised by a named solicitor. Specialist investigators and forensic professionals are introduced where their expertise is needed, with their role and status explained.",
      "Confirm current authorised individuals on the public SRA record. Job titles on this site are not a reserved-activity authorisation.",
    ],
  },
  {
    slug: "david-kerr",
    name: "David Kerr",
    shortName: "David Kerr",
    initials: "DK",
    role: "Lawyer — Fraud, Financial Crime & Private Prosecutions",
    firm: "Edison Law",
    featured: true,
    photo: "/images/people/david-kerr.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Lawyer in the financial crime team. Runs large, document-heavy matters from first instruction through to trial.",
    bio: [
      "David is a lawyer in the firm's financial crime team. David runs some of the firm's largest and most document-heavy matters from first instruction through to trial.",
      "He acts for companies, organisations and individuals who have been the victims of crime: boardroom and senior-management fraud, false accounting, misappropriation, procurement fraud, and losses through misrepresented investments. He is usually brought in once the problem is bigger than first thought, and his first task is to impose order on it.",
      "He conducts private prosecutions end to end — investigation, a criminal-standard file, disclosure, counsel and trial — on the basis that a sloppy case will not survive the defence. Recovery is settled at the outset: freezing, search and disclosure, restraint and confiscation, civil claims and insolvency where they reach the money faster.",
      "David is measured, decisive and good with clients under pressure. He supervises junior lawyers and insists every file can be picked up cold and understood.",
    ],
    experience: [
      "Private prosecutions of internal fraud, false accounting and misappropriation — investigation through to trial",
      "Emergency freezing, search and disclosure applications where value is still moving",
      "Parallel criminal, civil and insolvency strategy on the same facts",
      "Board-level internal investigations that may later have to be reported",
    ],
  },
  {
    slug: "amelia-rowe",
    name: "Amelia Rowe",
    shortName: "Amelia Rowe",
    initials: "AR",
    role: "Lawyer — Fraud, Financial Crime & Private Prosecutions",
    firm: "Edison Law",
    photo: "/images/people/amelia-rowe.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Lawyer in the financial crime team. Day-to-day conduct of cases from first instruction through to trial, and often the client's principal point of contact.",
    bio: [
      "Amelia is a lawyer in the firm's financial crime team. Amelia is closely involved in the day-to-day conduct of those cases, from first instruction through to trial.",
      "She acts for companies, organisations and individuals who have been the victims of crime: employee and fiduciary fraud, false accounting, misappropriation, supplier fraud and investment schemes affecting private individuals. She is often the client's principal point of contact in matters that are distressing as well as complex.",
      "She prepares case papers to a criminal evidential standard, drafts statements, manages disclosure, instructs counsel and attends court. Recovery work sits alongside: freezing, search and disclosure applications, tracing with forensic colleagues, and restraint, confiscation and civil claims at short notice.",
      "Amelia is precise, well organised and calm under pressure. Colleagues describe her as the person who has already found the document everyone else is still looking for.",
    ],
    experience: [
      "Case file and disclosure schedules in a private prosecution of a former employee for invoicing fraud",
      "Urgent freezing and search order following fiduciary misappropriation",
      "Acting for investors in a collapsed scheme, coordinating tracing and civil recovery",
      "Witness evidence and trial bundles in Crown Court proceedings",
    ],
  },
  {
    slug: "liam-brennan",
    name: "Liam Brennan",
    shortName: "Liam Brennan",
    initials: "LB",
    role: "Financial Crime Investigator",
    firm: "Edison Law",
    featured: true,
    photo: "/images/people/liam-brennan.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Financial crime investigator in the firm's team. Establishes what happened, with a particular focus on cross-border enquiry.",
    bio: [
      "Liam is a financial crime investigator within the firm's team. Liam's role is to establish what happened — who was involved, how the scheme operated, and what evidence exists to prove it — before a strategy is chosen.",
      "He works for companies, organisations and individuals who have been the victims of crime, with a focus on cross-border investigation. He has spent much of his career on matters spanning Ireland, the UK and the wider EU: foreign registries, court records, insolvency files and procurement databases.",
      "He builds files that hold up: witnesses, statements, continuity and disclosure. Recovery work is the same method — nominee directors, connected companies, family members holding property, and people who have moved or gone to ground — so freezing, service and enforcement have facts underneath them.",
      "Liam is patient and quietly effective. He rarely reports anything until he can prove it, and he has a habit of producing the one document that changes the shape of a case.",
    ],
    experience: [
      "Procurement fraud spanning three European jurisdictions, identifying links between a manager and a supplier network",
      "Location of a defendant who had relocated abroad under a variant of his name",
      "Foreign registry and court records establishing control of companies used to receive diverted funds",
      "Witness enquiries and statements supporting a Crown Court private prosecution",
    ],
  },
  {
    slug: "sophie-lang",
    name: "Sophie Lang",
    shortName: "Sophie Lang",
    initials: "SL",
    role: "Payments Tracing Specialist",
    firm: "Edison Law",
    photo: "/images/people/sophie-lang.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Payments tracing specialist in the financial crime team. Follows diverted funds through banks, PSPs and e-money accounts in the first hours of a matter.",
    bio: [
      "Sophie is a payments tracing specialist in the firm's financial crime team. Sophie is brought in when the question is where a payment went — today, not next month.",
      "She acts for companies, organisations and individuals who have been the victims of crime, particularly payment diversion and authorised push payment fraud. Working from incomplete references, she maps movement through correspondent banks, payment institutions and e-money accounts, and produces the picture needed for an emergency application.",
      "That early tracing becomes evidence: flow-of-funds schedules, institution lists, and the disclosure routes against each. She will say when the trail has left the regulated system, and when it has not.",
      "Sophie is quick, composed under pressure, and good at explaining a funds trail to people hearing it for the first time. Clients often say she was the first person to make the situation feel manageable.",
    ],
    experience: [
      "Payments map completed within two days of a seven-figure diversion, supporting a proprietary injunction",
      "Identification of layered transfers through multiple payment institutions",
      "Exhibits prepared for a private prosecution of a former employee who altered payee details",
      "Loss schedule for parallel civil proceedings and an insurance notification",
    ],
  },
  {
    slug: "oliver-bennett",
    name: "Oliver Bennett",
    shortName: "Oliver Bennett",
    initials: "OB",
    role: "Lawyer — Fraud, Financial Crime & Private Prosecutions",
    firm: "Edison Law",
    photo: "/images/people/oliver-bennett.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Lawyer in the financial crime team. Often the first person a client speaks to once a fraud surfaces: get hold of the matter, say what can be achieved, push it forward.",
    bio: [
      "Oliver is a lawyer in the firm's financial crime team. Oliver's practice sits at the operational heart of it: getting hold of a new matter fast, working out what can actually be achieved, and pushing it forward.",
      "He acts for companies, organisations and individuals who have been the victims of crime — director and employee fraud, false accounting, misappropriation, supplier fraud, and losses through dishonest investment arrangements. He is frequently the first person a client speaks to, and he gives a straight assessment, including when the answer is unwelcome.",
      "He prepares cases to a criminal evidential standard, manages disclosure, works with investigators and forensic experts, and attends throughout proceedings. Recovery runs through the same file: urgent freezing, search and disclosure, restraint and confiscation, and civil or insolvency claims where they reach the money faster.",
      "Oliver is direct, tenacious and steady with clients who are anything but. Colleagues say he gets a chaotic new file into order quicker than anyone expects.",
    ],
    experience: [
      "Private prosecution of a former director for misappropriation of company funds",
      "Freezing and disclosure applications issued within days of a fraud being discovered",
      "Parallel criminal and civil claims arising from supplier fraud",
      "Internal investigation into senior employee expenses and false invoicing",
    ],
  },
  {
    slug: "andrew-haddon",
    name: "Andrew Haddon",
    shortName: "Andrew Haddon",
    initials: "AH",
    role: "Asset Tracing Specialist",
    firm: "Edison Law",
    featured: true,
    photo: "/images/people/andrew-haddon.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Asset tracing specialist in the financial crime team. Locates recoverable value and says, early, whether pursuing it is worth the cost.",
    bio: [
      "Andrew is an asset tracing specialist within the firm's financial crime team. Andrew's role addresses the question every victim of fraud eventually asks: where has the money gone, and is any of it still there.",
      "He works for companies, organisations and individuals who have been the victims of crime. He follows funds from the point of loss through banks, payment institutions and corporate accounts, and identifies where proceeds have been converted — property, vehicles, investments, goods or digital assets — and in whose name they are held. Where a defendant appears to be worth nothing, he tests whether that is true.",
      "He produces tracing evidence that stands up in court: flow-of-funds schedules, asset registers and exhibits for restraint, confiscation and freezing. He assesses not only whether an asset can be found but whether pursuing it is economically worthwhile, including before litigation begins.",
      "Andrew is methodical, discreet and realistic. Clients are told early when there is value to pursue — and equally early when the trail ends.",
    ],
    experience: [
      "Tracing exercise across five jurisdictions establishing the destination of misappropriated group funds",
      "Identification of residential property held through a nominee, supporting a proprietary freezing order",
      "Asset register prepared for restraint and confiscation following conviction",
      "Pre-action enforceability assessment that redirected strategy toward a solvent third party",
    ],
  },
  {
    slug: "rosalind-keane",
    name: "Rosalind Keane",
    shortName: "Rosalind Keane",
    initials: "RK",
    role: "Confiscation Specialist",
    firm: "Edison Law",
    photo: "/images/people/rosalind-keane.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Confiscation specialist in the financial crime team. Turns a conviction or a settlement into a recoverable amount: benefit, available assets, and the orders that actually reach them.",
    bio: [
      "Rosalind is a confiscation specialist in the firm's financial crime team. Rosalind's job is the part that comes after the verdict: making sure the benefit figure, the available amount and the enforcement route are ready before anyone assumes the money will come back.",
      "She acts for companies, organisations and individuals who have been the victims of crime. She prepares confiscation and compensation files, tests what a defendant actually owns, and works with tracing and forensic colleagues so hidden value is on the schedule rather than discovered too late.",
      "Rosalind supports advice on which retrieval route the facts will carry — restraint, confiscation and civil enforcement as one sequence, not three afterthoughts. She is precise about what POCA will reach and what it will not.",
      "She is calm, exact and unwilling to inflate a figure that will not survive a hearing. Clients are told the recoverable position, not the hopeful one.",
    ],
    experience: [
      "Benefit and available-amount analysis following conviction in a private prosecution of a finance director",
      "Restraint varied after hidden property and nominee holdings were identified",
      "Compensation schedule prepared alongside confiscation so the victim's claim was not left to the end",
      "Enforcement against assets transferred to family members ahead of sentencing",
    ],
  },
  {
    slug: "julian-vance",
    name: "Julian Vance",
    shortName: "Julian Vance",
    initials: "JV",
    role: "Forensic Accountant",
    firm: "Edison Law",
    featured: true,
    photo: "/images/people/julian-vance.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Forensic accountant in the financial crime team. Rebuilds the books, states what the numbers prove, and writes reports that can be cross-examined.",
    bio: [
      "Julian is a forensic accountant in the firm's financial crime team. Julian's role is to turn disordered accounts into a financial narrative a court can follow.",
      "He acts for companies, organisations and individuals who have been the victims of crime. He reconstructs ledgers, unwinds intercompany transfers, quantifies loss and identifies the point at which money left the client's control. He will say, early, when the records do not support the allegation.",
      "His reports and schedules are written for trial, confiscation and civil recovery. He works with counsel on the figures that will actually be tested, and with investigators on the documents those figures need.",
      "Julian is measured and difficult to rush. Colleagues bring him the file when the story is bigger than the evidence.",
    ],
    experience: [
      "Reconstruction of manipulated management accounts establishing the mechanism of a long-running invoicing fraud",
      "Loss quantification supporting an emergency proprietary injunction",
      "Expert report and schedules prepared for a Crown Court private prosecution",
      "Transaction testing after internal fraud in a payments business",
    ],
  },
  {
    slug: "imogen-vale",
    name: "Imogen Vale",
    shortName: "Imogen Vale",
    initials: "IV",
    role: "Digital Forensics Analyst",
    firm: "Edison Law",
    photo: "/images/people/imogen-vale.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Digital forensics analyst in the financial crime team. Preserves devices, mailboxes and logs so the digital record still exists when the legal route is chosen.",
    bio: [
      "Imogen is a digital forensics analyst in the firm's financial crime team. Imogen's first task is preservation: hold the device, the mailbox and the log before anyone tidies the file.",
      "She acts for companies, organisations and individuals who have been the victims of crime. She images machines, captures accounts, records access, and produces exhibits with continuity intact. She will stop a well-meaning export that would destroy metadata.",
      "Her work feeds both investigation and recovery: payment records, deleted mail, device histories that show who moved what, and when. She writes method so it can be explained later, including under cross-examination.",
      "Imogen is exact, quiet and difficult to fluster. The team calls her before anyone logs in.",
    ],
    experience: [
      "Imaging of laptops and phones in the first day of an internal fraud, before accounts were reset",
      "Mailbox preservation supporting a private prosecution of a former employee",
      "Continuity records for digital evidence used on an urgent search order",
      "Recovery of deleted payment instructions showing a supplier diversion",
    ],
  },
  {
    slug: "caroline-reid",
    name: "Caroline Reid",
    shortName: "Caroline Reid",
    initials: "CR",
    role: "Lawyer — Restraint & Freezing",
    firm: "Edison Law",
    photo: "/images/people/caroline-reid.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Lawyer in the financial crime team, focused on restraint and freezing. Prepares the application that stops the money moving, then keeps the order in place.",
    bio: [
      "Caroline is a lawyer in the firm's financial crime team, with a practice in restraint and freezing. Caroline is instructed when value is still moving and a delay will cost the client the asset.",
      "She acts for companies, organisations and individuals who have been the victims of crime. She prepares worldwide and proprietary freezing applications, Bankers Trust and Norwich Pharmacal orders, and the evidence packs those applications require — often on very short notice.",
      "Asset recovery is the point of the work, not a sequel. Caroline coordinates with tracing and forensic colleagues so the order names the right institutions, and she manages the undertakings and variations that follow.",
      "She is organised, direct with clients under pressure, and careful not to ask a court for more than the evidence will carry.",
    ],
    experience: [
      "Worldwide and proprietary freezing applications where a fiduciary's misappropriation has just come to light",
      "Proprietary injunctions supported by a payments-tracing picture assembled in days",
      "Disclosure orders against banks holding diverted balances",
      "Variation and enforcement of freezing orders after assets are moved into a nominee's name",
    ],
  },
  {
    slug: "marcus-quinn",
    name: "Marcus Quinn",
    shortName: "Marcus Quinn",
    initials: "MQ",
    role: "Crypto Tracing Analyst",
    firm: "Edison Law",
    featured: true,
    photo: "/images/people/marcus-quinn.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Crypto tracing analyst in the financial crime team. Maps wallets, exchanges and cash-outs, and states what on-chain data can and cannot prove.",
    bio: [
      "Marcus is a crypto tracing analyst in the firm's financial crime team. Marcus maps where digital value went — through wallets, mixers, bridges and exchanges — without pretending the chain shows more than it does.",
      "He acts for companies, organisations and individuals who have been the victims of crime, including wallet theft, investment scams and conversion of diverted fiat into digital assets. He produces clustering, hop maps and exchange-attribution that can be exhibited, and he flags when a hop is inference rather than fact.",
      "His work supports emergency applications against exchanges and the later trial file. He liaises on freeze requests and writes the limits of the tracing into the report, so counsel is not surprised in court.",
      "Marcus is precise and unimpressed by theatre. He will say when the coins have cashed out, and when they have not.",
    ],
    experience: [
      "Wallet mapping supporting an emergency freeze request to a regulated exchange",
      "Tracing of proceeds converted from a payment diversion into digital assets and back into banking",
      "Exhibits for a private prosecution involving an unregulated trading platform",
      "Attribution report distinguishing confirmed exchange deposits from inferred clustering",
    ],
  },
  {
    slug: "robert-hale",
    name: "Robert Hale",
    shortName: "Robert Hale",
    initials: "RH",
    role: "Senior Asset Recovery Specialist",
    firm: "Edison Law",
    featured: true,
    photo: "/images/people/robert-hale.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Senior asset recovery specialist in the financial crime team. Decides which assets are worth reaching, in which order, and by which remedy.",
    bio: [
      "Robert is a senior asset recovery specialist in the firm's financial crime team. Robert holds the recovery strategy: which asset, which court, which order, and at what cost.",
      "He acts for companies, organisations and individuals who have been the victims of crime. He works from tracing and intelligence already in hand, then sequences freezing, disclosure, receivership and enforcement so effort is not spent on value that cannot be reached.",
      "He coordinates local counsel overseas, insolvency routes where they are faster, and the difference between an asset that exists and an asset that can be sold. He will advise against a chase that will cost more than it returns.",
      "Robert is commercial and unsentimental. Clients get a plan, and they get told when the plan should stop.",
    ],
    experience: [
      "Recovery strategy combining a proprietary freeze, disclosure against banks and later receivership",
      "Enforcement against property held through a nominee after tracing identified the true controller",
      "Insolvency route used to reach assets faster than a free-standing claim",
      "Decision to abandon overseas enforcement where the cost exceeded likely recovery",
    ],
  },
  {
    slug: "clara-whitfield",
    name: "Clara Whitfield",
    shortName: "Clara Whitfield",
    initials: "CW",
    role: "Lawyer — Disclosure & Unused Material",
    firm: "Edison Law",
    photo: "/images/people/clara-whitfield.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Lawyer in the financial crime team. Builds the unused-material schedule so a private prosecution still holds when the defence tests it.",
    bio: [
      "Clara is a lawyer in the firm's financial crime team. Clara's work is disclosure: what must be scheduled, what is unused, and what would destroy the case if it were left in a drawer.",
      "She acts for companies, organisations and individuals who have been the victims of crime. She is brought in once a file is heading toward charge or a contested hearing, and her first task is to read it as a defence solicitor would.",
      "She drafts CPIA schedules, unused-material notes and the correspondence that keeps the duty of candour honest. Recovery sits in the same file: she will flag a document that helps a freeze as readily as one that hurts a prosecution.",
      "Clara is exact and unhurried. She will stop a charging decision that the unused material cannot survive.",
    ],
    experience: [
      "Unused-material schedules prepared for a Crown Court private prosecution of internal fraud",
      "Disclosure review before a charging decision on a document-heavy misappropriation",
      "Continuity and exhibit lists for digital and financial material on the same file",
      "Advice to pause a prosecution where the unused material would not hold",
    ],
  },
  {
    slug: "thomas-ellery",
    name: "Thomas Ellery",
    shortName: "Thomas Ellery",
    initials: "TE",
    role: "Lawyer — Fraud, Financial Crime & Private Prosecutions",
    firm: "Edison Law",
    photo: "/images/people/thomas-ellery.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Lawyer in the financial crime team. Takes a new fraud file in hand, says what the evidence will carry, and runs it through to charge or a decision to stop.",
    bio: [
      "Thomas is a lawyer in the firm's financial crime team. Thomas is usually on the file from the first week: hold what still exists, say whether a criminal case is realistic, and start the work that a later trial will need.",
      "He acts for companies, organisations and individuals who have been the victims of crime — employee and director fraud, false accounting, supplier diversion and dishonest investment arrangements. He gives a straight first view, including when the facts will not meet the criminal standard.",
      "He prepares statements, manages the early evidential file, works with investigators and forensic specialists, and instructs counsel when advocacy is needed. Recovery is sequenced with the criminal work so a freeze is not an afterthought.",
      "Thomas is composed under pressure and careful not to promise a conviction the papers cannot support.",
    ],
    experience: [
      "Early merit and cost advice on whether a declined police report can still be prosecuted",
      "Case papers and witness statements in a private prosecution of supplier fraud",
      "Urgent hold of devices and accounts in the first days of an internal fraud",
      "Parallel advice on a proprietary freeze while the criminal file is still being built",
    ],
  },
  {
    slug: "hannah-croft",
    name: "Hannah Croft",
    shortName: "Hannah Croft",
    initials: "HC",
    role: "Internal Investigations Specialist",
    firm: "Edison Law",
    photo: "/images/people/hannah-croft.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Internal investigations specialist. Runs board-level, employee and whistleblower enquiries so the file still holds if you later prosecute, report or litigate.",
    bio: [
      "Hannah is an internal investigations specialist in the firm's team. Hannah's work starts when a whistleblower report, a gap in the accounts or unexplained payments has reached the board — and before anyone is dismissed or reported on a file that will not stand up.",
      "She acts for companies, organisations and trustees. She identifies hold, access and privilege before interviews begin, and she writes for the next reader: a regulator, a defendant or a judge, not only the board that instructed her.",
      "She coordinates device preservation, employee interviews and the document hold so an HR process is not passed off as an evidential investigation. She will say when a predetermined finding would wreck both the employment outcome and any later prosecution.",
      "Hannah is discreet and difficult to rush. She reports what the material supports, including when that is not what the board hoped to hear.",
    ],
    experience: [
      "Hold, access and privilege scoping in the first 48 hours of a whistleblower report",
      "Employee interviews run so the record can later support a private prosecution",
      "Internal enquiry into falsified invoicing written for a possible regulatory notification",
      "Advice to separate an employment process from the evidential file",
    ],
  },
  {
    slug: "hugh-penton",
    name: "Hugh Penton",
    shortName: "Hugh Penton",
    initials: "HP",
    role: "Lawyer — Regulatory Defence & Investigations",
    firm: "Edison Law",
    photo: "/images/people/hugh-penton.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Lawyer in the financial crime team. Represents individuals and companies when an SFO, FCA or HMRC enquiry is already underway.",
    bio: [
      "Hugh is a lawyer in the firm's financial crime team, with a practice in regulatory defence and investigations. Hugh is instructed when a dawn raid, an interview under caution or an information notice has already landed.",
      "He acts for individuals and companies under investigation by the SFO, FCA, HMRC and other bodies. The work is the quality of the file — hold, privilege, who speaks — not a claim that an enquiry can be closed because of who he used to know.",
      "He advises on interviews under PACE, the scope of what must be said, and whether a civil settlement or a report is the honest next step. Recovery against a third party can run in parallel where the facts support it; he will not pretend the two cannot collide.",
      "Hugh is measured and exact. He will not give a blanket yes or no on a website, and he will not volunteer a story to a regulator in hope.",
    ],
    experience: [
      "First-hours advice on hold, privilege and who speaks after a search under warrant",
      "Representation at interviews under caution where the papers and PACE decide the approach",
      "Responses to information notices scoped to what is required, not to a hopeful narrative",
      "Sequencing of regulatory defence with a recovery claim against a third party",
    ],
  },
  {
    slug: "edward-langford",
    name: "Edward Langford",
    shortName: "Edward Langford",
    initials: "EL",
    role: "Lawyer — Cross-Border Fraud & Corruption",
    firm: "Edison Law",
    photo: "/images/people/edward-langford.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Lawyer in the financial crime team. Holds the London file where a UK-facing loss has its origins, or its proceeds, overseas.",
    bio: [
      "Edward is a lawyer in the firm's financial crime team. Edward's practice is cross-border fraud and corruption: evidence, freezing and enforcement where the people or the money sit outside England and Wales.",
      "He acts for companies, organisations and individuals who have been the victims of crime with a UK-facing loss and overseas facts. He maps forum, asset and defendant before anyone files, and he instructs local counsel where the money actually sits — not by listing offices the firm does not have.",
      "He sequences service out, letters of request, recognition and enforcement so one court does not ambush another. He will advise against English process that a foreign court will not recognise, and against a chase that will cost more than it returns.",
      "Edward is methodical and commercially minded. Clients get a jurisdiction picture, and they get told when recognition will fail.",
    ],
    experience: [
      "Forum and asset mapping before issue where defendants and value sat in more than one country",
      "Instruction of local counsel for registry and enforcement steps where the money sat",
      "Advice on recognition of a foreign judgment or award in England, or of an English order abroad",
      "Decision to stop overseas enforcement where the economics would not hold",
    ],
  },
  {
    slug: "daniel-crowe",
    name: "Daniel Crowe",
    shortName: "Daniel Crowe",
    initials: "DC",
    role: "Financial Crime Investigator",
    firm: "Edison Law",
    photo: "/images/people/daniel-crowe.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Financial crime investigator. Establishes who was involved, how the scheme ran, and what the documents actually prove — before anyone commits to a legal route.",
    bio: [
      "Daniel is a financial crime investigator within the firm's team. Daniel's role is to establish the facts of a fraud, false accounting or misappropriation before a private prosecution, a freeze or a regulatory report is chosen.",
      "He acts for companies, organisations and individuals who have been the victims of crime. He works from the documents, the people and the accounts that still exist, and he writes a file that could later be picked up by a defence solicitor without embarrassment.",
      "He identifies witnesses, gathers records and tests a narrative against unused material. Recovery work is the same method: who received the money, in whose name it sits, and whether they can be found.",
      "Daniel is patient and precise. He rarely reports a finding until he can exhibit it.",
    ],
    experience: [
      "Evidential file for a financial crime investigation after a report to Action Fraud produced nothing usable",
      "Witness enquiries and document hold following discovery of a gap in the accounts",
      "Continuity records for a file that later supported a private prosecution",
      "Enquiries identifying the recipient of diverted supplier payments",
    ],
  },
  {
    slug: "simon-blake",
    name: "Simon Blake",
    shortName: "Simon Blake",
    initials: "SB",
    role: "Lawyer — Crypto Fraud & Digital Assets",
    firm: "Edison Law",
    photo: "/images/people/simon-blake.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Lawyer in the financial crime team. Turns an on-chain picture into a legal decision: freeze, letter, claim — or a statement of what the records cannot prove.",
    bio: [
      "Simon is a lawyer in the firm's financial crime team, with a practice in crypto fraud and digital assets. Simon is instructed when value has moved across wallets, mixers, bridges or exchanges, and someone needs to know what a court in England and Wales will actually take from that trail.",
      "He acts for companies, organisations and individuals who have been the victims of crime. He works with tracing analysts so clustering, hop maps and exchange-attribution are exhibited with their limits stated — inference marked as inference.",
      "He advises on freeze requests to regulated platforms, proprietary claims, and whether a private prosecution or a civil route is realistic. He will not treat a wallet trail as a defendant, and he will not guarantee that coins come back.",
      "Simon is precise and unimpressed by screenshots. He writes the limits of the tracing into the advice so counsel is not surprised later.",
    ],
    experience: [
      "Legal advice on an emergency freeze request to a regulated exchange, based on exhibited wallet mapping",
      "Proprietary claim where diverted fiat had been converted into digital assets and back into banking",
      "Advice that on-chain clustering was inference, not proof of control, before proceedings were issued",
      "Case papers coordinating tracing exhibits with a later private prosecution of an unregulated platform",
    ],
  },
  {
    slug: "helen-ashworth",
    name: "Helen Ashworth",
    shortName: "Helen Ashworth",
    initials: "HA",
    role: "Lawyer — Tax Investigations & HMRC",
    firm: "Edison Law",
    photo: "/images/people/helen-ashworth.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Lawyer in the financial crime team. Separates the documents that decide an HMRC enquiry from the volume that merely surrounds it.",
    bio: [
      "Helen is a lawyer in the firm's financial crime team, with a practice in tax investigations and HMRC enquiries. Helen's work is the file that answers a defined question: what the notice actually asks, what privilege protects, and what would create a new question if it were sent.",
      "She acts for companies, organisations and individuals facing an enquiry, an information notice or a dispute that may move toward a different procedure. She lists the questions asked, the documents that answer them, and the documents that should not be volunteered.",
      "Where the same facts may later support a fraud allegation, a freeze or a report, she keeps the evidential file honest. This is not tax-return preparation, and it is not a promise that an enquiry will close on any timetable.",
      "Helen is organised and direct. She prefers a focused disclosure to a hopeful volume.",
    ],
    experience: [
      "Scoped response to an HMRC information notice, limited to the questions actually asked",
      "Privilege review before documents were sent in a document-heavy enquiry",
      "Working file separating the papers that decide a tax dispute from surrounding volume",
      "Advice where an enquiry was moving toward a different procedure, including possible fraud issues",
    ],
  },
  {
    slug: "graham-holt",
    name: "Graham Holt",
    shortName: "Graham Holt",
    initials: "GH",
    role: "Pre-Litigation Intelligence Specialist",
    firm: "Edison Law",
    photo: "/images/people/graham-holt.png",
    photoWidth: 273,
    photoHeight: 273,
    summary:
      "Pre-litigation intelligence specialist. Establishes who a counterparty is, what they own, and whether a claim is worth the cost — before money is spent.",
    bio: [
      "Graham is a pre-litigation intelligence specialist in the firm's team. Graham's work sits before the first letter: who the other side actually is, whether they can satisfy a judgment, and whether the appointment or the transaction should proceed at all.",
      "He acts for companies, organisations and individuals instructing enhanced due diligence before a high-value transaction, investment or appointment, and for victims of crime who need to know whether a defendant is worth pursuing. He maps connected companies, undisclosed litigation and assets held through nominees, using open-source and registry work first.",
      "His findings inform recovery strategy as much as they inform whether to instruct. Visible steps are taken only on instruction. He will not overstate a connection he cannot prove.",
      "Graham is discreet and commercially minded. Clients get a short answer when the trail is thin, and a plan when it is not.",
    ],
    experience: [
      "Pre-action intelligence showing a judgment against a counterparty would not be worth enforcing",
      "Source-of-wealth and integrity review before a high-value appointment",
      "Mapping of connected companies used to receive diverted funds, before a freeze was sought",
      "Advice to proceed no further where registry and litigation records did not support the proposed claim",
    ],
  },
];
